### ISSUE TITLE
help: Dependency injection at the plugin level

### ISSUE THREAD

**Issue by lewebsimple** [nuxt-community/composition-api#104]
**📚 What are you trying to do? Please describe.**
I'm trying to `provide` a value on the root Vue instance, and then `inject` this inside the various components / pages / layouts. 

**🔍 What have you tried?**
I tried calling `provide` from `setup()` inside `layouts/default.vue`as was suggested in a couple of places, which kind of worked, but it doesn't look very clean to me (plus I'd need to have this code in every layout .... not very DRY)

I also tried creating a Nuxt plugin, which seemed like the proper way to do this, but the global [provide / inject method described in the proposed RFC](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0009-global-api-change.md#provide--inject) isn't available.

I also encountered the suggestion of [assigning a new `setup` function to app](https://stackoverflow.com/a/59270760/7146260), but this seems like it would break as soon as another plugin also assigns its own setup function.

**ℹ️ Additional context**
Having some kind of `onSetup` hook available in plugins or global `provide` would solve this kind of issue, people using `vue-apollo-composable` would have a cleaner way of providing the apollo client.

I'm not sure how dependency injection interacts with SSR and if `provide` could be used independently on the server and client Vue instance.

**Comment by danielroe** [comment]
@lewebsimple Thanks for the report. Try `onGlobalSetup` in v0.9.2 - and let me know what you think :smiley:

**Comment by lewebsimple** [comment]
Fantastic job !
