### ISSUE TITLE
fix: import of ComponentInstance fails

### ISSUE THREAD

**Issue by MartinMalinda** [nuxt-community/composition-api#110]
**🐛 The bug**
```
5:35 Cannot find module '@vue/composition-api/dist/component' or its corresponding type declarations.
    3 | import { Context } from '@nuxt/types';
    4 | import { Route } from 'vue-router';
  > 5 | import { ComponentInstance } from '@vue/composition-api/dist/component';
      |                                   ^
    6 | import { MetaInfo } from 'vue-meta';
    7 | 
    8 | /**
```

**🛠️ To reproduce**
`"@vue/composition-api": "^0.6.1",`
`"nuxt-composition-api": "^0.9.0",`

It seems like this type is not exported?

**Comment by danielroe** [comment]
@MartinMalinda It looks like this was caused by some breaking type changes in https://github.com/vuejs/composition-api/releases/tag/v0.6.2.

**Comment by danielroe** [comment]
@MartinMalinda Let me know if `v0.9.1` doesn't fix this for you.
