### ISSUE TITLE
feat: use Nuxt lifecycle hooks

### ISSUE THREAD

**Issue by MartinMalinda** [nuxt-community/composition-api#112]
https://nuxtjs.org/api/internals-renderer

I guess these hooks are not intended to be used in components in general, but with some of them it would actually make sense to me.

My specific usecase would be `render:routeContext`. It could provide an alternative to `ssrRef`. I could serialize anything in a custom way just at the last moment. My custom hook is returning a `reactive` object and only some of the state makes sense to serialize (there's a bunch of derived state).

(This is what I'm working on: https://vue-concurrency.netlify.app/ssr-support/)

```ts
onSetupContext((context, sanitize) => {
 context[myKey] = sanitize(someCustomSerialization(obj));
});

**Comment by danielroe** [comment]
@MartinMalinda Is there any chance that this is what you're looking for?

```ts
import { useContext } from 'nuxt-composition-api'

export default defineComponent({
  setup() {
    const { beforeNuxtRender } = useContext()

    beforeNuxtRender((comps, nuxtState) => {
      nuxtState[myKey] = sanitize(someCustomSerialization(obj));
    })
  }
})
```

**Comment by MartinMalinda** [comment]
This is what I was looking for! But in the mean time I figured out that `onServerPrefetch` is probably enough for my usecase:

https://ssr.vuejs.org/api/#serverprefetch
> Fetch async data during server side rendering. It should store fetched data into a global store and return a Promise. The server renderer will wait on this hook until the Promise is resolved. This hook has access to the component instance via this.

Before I just thought `onServerPrefetch` is just for returning a promise.
There could be differences between `beforeNuxtRender` and `onServerPrefetch`, but otherwise I believe this could be closed.

**Comment by danielroe** [comment]
Okay, I'll close this then but if you or anyone else has particular needs I'm open to exposing Nuxt lifecycle hooks.
