### ISSUE TITLE
I want to setting the metaInfo before client side render~

### ISSUE THREAD

**Issue by cjfff** [nuxt-community/composition-api#116]
**📚 What are you trying to do? Please describe.**
I want to setting the metaInfo before client side render~

I see the doc, use the useMeta funciton;

It can run, but it is not accord with my expect.

I expect the metaInfo can generate before the page client rendered

![image](https://user-images.githubusercontent.com/20502762/84576999-56004700-adeb-11ea-872c-e5cb2e580577.png)

i think the metaInfo can run in fetch function inside can fixed it

![image](https://user-images.githubusercontent.com/20502762/84576991-4a148500-adeb-11ea-927a-fac0944405eb.png)

**🔍 What have you tried?**
I try to use three functions to do, but not one can resolve my problem;
1. useAysnc
2. useFetch
3. onServerPrefetch

**Comment by danielroe** [comment]
@cjfff Would you be able to provide a reproduction on GitHub or CodeSandbox?

**Comment by cjfff** [comment]
> @cjfff Would you be able to provide a reproduction on GitHub or CodeSandbox?

yes, you can access the [link](https://codesandbox.io/s/reverent-field-t9izn?file=/pages/posts/_id.vue)

and you can look the useMeta usage

**Comment by cjfff** [comment]
I resolve it  by this usage,  so  i close the issue now.  

```js
const { title, meta } = useMeta()

useFetch(async () => {
  const data  = await someAjax();

 title.value.title = data.title
 meta.value = [
    {
    hid: "description",
    "name": "description",
    "content": data.description
    }
  ]
})
```

**Comment by danielroe** [comment]
Great ❤️
