### ISSUE TITLE
help: Is there a way to use Jest with 'nuxt-composition-api'

### ISSUE THREAD

**Issue by tcastelly** [nuxt-community/composition-api#129]
Hello,

I'm trying to test a component using 'nuxt-composition-api' with Jest.

I'm wondering if there is a tip to mock 'nuxt-composition-api' with '@vue/composition-api' to be able to test.

Error message:
```
/home/shenron/Documents/dev/workspaces/js/vue/vue-nuxt-tsx/node_modules/nuxt-composition-api/lib/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { resolve, join } from 'path';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

**Comment by danielroe** [comment]
@tcastelly Add this to your `jest.config`:

```js
  moduleNameMapper: {
    // ...
    'nuxt-composition-api': 'nuxt-composition-api/lib/cjs/entrypoint.js',
  },
```

Let me know if that works for you :slightly_smiling_face:

**Comment by tcastelly** [comment]
It works! Thank a lot! :)

I'm sorry I have a other linked question. How can I mock properly the `useFetch` hook?

**Comment by danielroe** [comment]
@tcastelly I think it will depend very much on your use case and what you're trying to test. Sorry not to be of more help!

**Comment by tcastelly** [comment]
No problem, thanks a lot for your help.

**Comment by wesley3295** [comment]
Currently using Nuxt 2 with composition/api. I am importing all the composition api functions into the nuxt.config.js file. When creating a jest.setup.js file I create a new Nuxt instance to use in jest adding the nuxtConfig.default. I have this setup file to run on globalSetup inside my jest.config.js file. I get an error saying the composition api functions inside the 
nuxt.config file cannot be reexported. This error occurs on all composition api functions individually. How do I bypass this or simply fix the problem?

**Comment by ibrahimBeladi** [comment]
@danielroe 
Any updates on this?
This is breaking our tests and providing us with a bad developer experience.
