### ISSUE TITLE
docs: example of how to use with component lifecycle events

### ISSUE THREAD

**Issue by shaunc** [nuxt-community/composition-api#136]
**📚 Is your documentation request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I feel I should be able to [...] but I can't see how to do it from the docs.

The issue from which composition-api sprung concerned component lifecycle events. This package seems to solve some of the problems, but I'm wondering what to do about `mounted` and `beforeDestroy` ... when are they called wrt to setup() and how to interact with them?
**🔍 Where should you find it?**
What page of the docs do you expect this information to be found on?

**ℹ️ Additional context**
Add any other context or information.

I am trying to use tiptap example here: https://github.com/scrumpy/tiptap/issues/131#issuecomment-555908852 I want to use state that is wired up in setup() in mounted(). **Or** simply do something "composition-api-like" instead of `beforeDestroy`.

**Comment by danielroe** [comment]
@shaunc This [reference](https://composition-api.vuejs.org/api.html#lifecycle-hooks) should help 🙂

**Comment by shaunc** [comment]
Ah great! Thanks! ... I guess since its "background I should know in order to use the composition api" it doesn't need to be documented in this adapter. You might want to have a link to the composition api doc somewhere prominent for people, like me, who need a hint. :)

**Comment by danielroe** [comment]
Great idea - and done :slightly_smiling_face:
