### ISSUE TITLE
fix: generated composition-api/index.js file fails on windows

### ISSUE THREAD

**Issue by kedrzu** [nuxt-community/composition-api#137]
**🐛 The bug**
On windows, when generating file `.nuxt/composition-api/index.js`, here is what happens:
![image](https://user-images.githubusercontent.com/2473784/86237914-e933cd80-bb9c-11ea-9942-7e9c0a2317ee.png)

Because windows by default uses backaslashes as path separators, they have to be properly escaped, or otherwise are treated as escape characters, and result in invalid string.

Here is the line of code, that produces that result.
https://github.com/nuxt-community/composition-api/blob/37dadfff654d5f0077028cec7a1a2ce4f6b4632d/src/index.ts#L29

I checked code from `@nuxt/vue-app` that generates routes, and it uses `relativeTo` function from `@nuxt/utils`. I checked it locally and it works, but I'm not sure if relative path here is fine.

Would love to give you PR, but I was not be able to easily run the source code locally on my windows 😐.

**🛠️ To reproduce**
Try to build app on windows.

**🌈 Expected behaviour**
Should compile, even on windows 😉

**Comment by danielroe** [comment]
This should now be fixed in v0.10.6. Let me know if it works for you 😃
