### ISSUE TITLE
feat: defineNuxtPlugin

### ISSUE THREAD

**Issue by simplesmiler** [nuxt-community/composition-api#157]
**🆒 Your use case**
When writing a typed Nuxt plugin, developer currently needs to do this:
```ts
import { Plugin } from '@nuxt/types';
const plugin: Plugin = (ctx) => {
   //
};
export default plugin;
```
The downside is that export is separate from definition.

**🆕 The solution you'd like**
A type helper would be nicer, e.g.:
```ts
import { defineNuxtPlugin } from 'nuxt-composition-api';
export default defineNuxtPlugin((ctx) => {
  //
});
```

I propose `defineNuxtPlugin` and not just `definePlugin`, because Vue itself has a concept of plugins, so there is a possibility for export name conflicts.

**Comment by simplesmiler** [comment]
Will be happy to make a PR if this gets the green light.

**Comment by mathe42** [comment]
So you just want a helper

```ts
import { Plugin } from '@nuxt/types';

export const defineNuxtPlugin = (plugin: Plugin) => plugin
```

I don't think this noop function should be in this module...

@danielroe what are your thoughts?

[EDIT] on second tought it might help developers (only TS)... And if it is treeshakable why not...

**Comment by danielroe** [comment]
I agree with @mathe42. This would be a great addition and would allow JS developers to benefit from type inference.

Probably worth adding other helpers, e.g. middleware.

**Comment by mathe42** [comment]
We can add these helpers - don't know if we need anything for Vuex because I don't use that:

```ts
import { Middleware, Plugin, Module, ServerMiddleware } from '@nuxt/types'

export const defineNuxtPlugin = (plugin: Plugin) => plugin
export const defineNuxtMiddleware = (middleware: Middleware) => middleware 
export const defineNuxtModule = <T={}>(module: Module<T>) => module 
export const defineNuxtServerMiddleware = (serverMiddleware: ServerMiddleware) => serverMiddleware
```

see https://typescript.nuxtjs.org/

**Comment by NickBolles** [comment]
@mathe42 @simplesmiler @danielroe, These are awesome, but I'm wondering if these should just be part of `@nuxt/types` or `@nuxt/typescript`? 

@kevinmarrec what do you think?

**Comment by danielroe** [comment]
@NickBolles Yes, I think these should ultimately be part of Nuxt itself. Plus probably a `defineNuxtConfig()` helper.
