### ISSUE TITLE
fix: Ref was not found in 'nuxt-composition-api'

### ISSUE THREAD

**Issue by Quineone** [nuxt-community/composition-api#163]
**🐛 The bug**
Run lint then error: 
![image](https://user-images.githubusercontent.com/15320933/87895276-8e90e180-ca77-11ea-89ec-077d26bfaecb.png)

**ℹ️ Additional context**
bug on version: "nuxt-composition-api": "^0.10.6",

by the way, work fine on version: "nuxt-composition-api": "^0.6.3"

**Comment by danielroe** [comment]
That looks like an eslint error. Try:
```ts
import type { Ref } from 'nuxt-composition-api'
```

**Comment by Quineone** [comment]
> That looks like an eslint error. Try:
> 
> ```ts
> import type { Ref } from 'nuxt-composition-api'
> ```

Hi @danielroe , that's work, thx. Expect can be fixed without using `type` like the old version did.

**Comment by danielroe** [comment]
@Quineone This may be helpful for you: https://github.com/typescript-eslint/typescript-eslint/issues/154

Note the discussion about the `import/named` rule.

**Comment by Quineone** [comment]
@danielroe Thank you for the quick response!

**Comment by mathieutu** [comment]
Hi @danielroe.
Actually we do not have any issue about other typed named import (in projects, or other packages). 

Only those with this package. Maybe is there something particular here?
