### ISSUE TITLE
fix: fetchOnServer always true with @vue/apollo-composable

### ISSUE THREAD

**Issue by tcastelly** [nuxt-community/composition-api#177]
**🐛 The bug**
With a "simple" http request I can toggle 'fetchOnServer' it works, same with `@nuxtjs/apollo`. But with `@vue/apollo-composable` all queries are fetch on server.

**🛠️ To reproduce**
Launch the repo:
https://github.com/shenron/vue-nuxt-tsx

There a 3 pages:
- index.vue, an http `fetchOnServer = false`
- graphql.vue, `prefetch: false`
- graphql_composition.vue, an `fetchOnServer = false`

**🌈 Expected behaviour**
To be able to swich `fetchOnServer`

Thank you for your help.

**Comment by danielroe** [comment]
@tcastelly A few comments

1. `fetchOnServer` just governs the behaviour of the new Nuxt `fetch()` API (including `useFetch`, and as far as I'm aware has no effect on Apollo. But maybe I'm misunderstanding your question?

2. You would include this parameter in your component options, not as second argument to `defineComponent`.

**Comment by tcastelly** [comment]
1. I'm sorry I was not clear. And I was wrong. I would want to be able to fetch queries defined by `@vue/apollo-composable` by the client.

Because it works with the default component creation
```javascript
export default {
  name: 'Graphql',
  apollo: {
    testQuery: {
      prefetch: false, // <--
      query: TestQuery,
    },
  },
}
```

But not with the `composition-api`
```javascript
export default defineComponent({
  setup() {
    const { result } = useQuery(TestQuery, {}, {
      prefetch: false, // <--
    });

    return {
      result,
    };
  },
});
```
I thought maybe it's linked to the `composition-api`.

2. Oups ... Thank you.

The current behavior that I have, is a pending query. If I replace the `prefetch: false` by `fetchPolicy: 'no-cache'` I have an Ajax query AND a fetch by the server.
```javascript
export default defineComponent({
  setup() {
    const { result } = useQuery(TestQuery, {}, {
      fetchPolicy: 'no-cache',
      //      prefetch: false,
    });

    return {
      result,
    };
  },
});
```

Thank you again for your help.

**Comment by danielroe** [comment]
@tcastelly This is perplexing, I grant you! But I'd suggest raising this as an issue with `@vue/apollo` as there should be no behaviour from `nuxt-composition-api` that should interfere with `useQuery`.

**Comment by tcastelly** [comment]
OK, I created an issue on `@vue/apollo`.
Thank you for your help!

https://github.com/vuejs/vue-apollo/issues/1022

**Comment by danielroe** [comment]
Do come back to me if there's anything I can do to help 🙂

**Comment by tcastelly** [comment]
Hello,

Until now I don't have any answer from @vue/apollo. I don't know if you have some clues.
Because it's a pending query in Nuxt, I'm wondering if it's not due to a lazy watch.

If I try to watch the `result`, there is no change.

Thank you for your help.

**Comment by danielroe** [comment]
@tcastelly You're right, it looks like `{ immediate: true }` is being set in the `useQuery` code. Perhaps you could [try reproducing](https://vue.new) the issue with `@vue/composition-api` but without Nuxt. If you can't reproduce it, then that suggests it is an issue to do with Nuxt or with this library.
