### ISSUE TITLE
fix: useAsync in ssr site doesn't reliably fetch content

### ISSUE THREAD

**Issue by Dan503** [nuxt-community/composition-api#182]
**🐛 The bug**
`useAsync` in a server side rendered site doesn't reliably fetch content.

**🛠️ To reproduce**

Clone this repository: https://github.com/Dan503/Stuart-McMillen-website/tree/useAsync-bug

**Note:** If you look at `pages/index.vue` you will see that a series of posts should get rendered at the bottom of the page.

```pug
.posts
	article.posts(v-for="post in posts")
		h3 {{post.title.rendered}}
		div(v-html="post.excerpt.rendered")
```
 
1. Run `npm run start`
2. Open http://localhost:3000/

Notice that the posts are not getting rendered onto the page. 

If they _are_ getting rendered, then refresh the page using the browser refresh button. The posts should now definitely not be visible.

You can sometimes get the posts to display by triggering recompile by editing a file.

**🌈 Expected behaviour**

Well firstly I was expecting `useAsync` to pre-fill the content on the server side if I'm server side rendering.

If that's not an option, then I would at least want the content to reliably load every time the page is loaded.

**ℹ️ Additional context**

I can only make this repository public for a limited time. Please let me know when it is safe for me to make it private again.

**Comment by danielroe** [comment]
@Dan503 I have cloned the repo and you can make it private again now. I'll have a look.

**Comment by mathe42** [comment]
Just did the same :O...

The problem is that your useAsync method returns a Promise of a Promise (res.json() returns a promise)

Changing your code to
```js
                const posts = useAsync(async () => {
			const res = await fetch(
				'https://css-tricks.com/wp-json/wp/v2/posts?page=1&per_page=20&_embed=1',
			)
			return res.json()
		})
```

fixes ist.

I will look into it if I can change `useAsync` to work with your example...

**Comment by Dan503** [comment]
Thanks,

I based the code I wrote off the documentation written here:

https://composition-api.now.sh/useAsync

```js
const posts = useAsync(() => axios.get('/api/posts'))
```

I just adjusted it to use the normal fetch API instead

```js
const posts = useAsync(() =>
	fetch(
		'https://css-tricks.com/wp-json/wp/v2/posts?page=1&per_page=20&_embed=1',
	).then((res) => res.json()),
)
```

Should the documentation be updated?

**Comment by Dan503** [comment]
Also, I'm having issues running the site on localhost in Firefox, is that a known issue?

Thankfully it seems to run ok in Firefox in production mode so it isn't a major issue.

**Comment by danielroe** [comment]
@Dan503 I use FF in dev with no issues.

**Comment by nvitaterna** [comment]
This may be related to #210. `useAsync`  checks for `instanceof Promise`. I did a quick check:
```js
const x = axios.get('/')
console.log(x instanceof Promise) // false
```

**Comment by danielroe** [comment]
@Dan503 Would you see if your issue persists with `v0.12.2`, or whether it's now solved?

**Comment by Dan503** [comment]
If i remember, I'll test it out tomorrow night

**Comment by Dan503** [comment]
@danielroe I tried running `npm i nuxt-composition-api@0.12.2` but it says that the version doesn't exist on npm. 

Did you publish it?

```
$ npm i nuxt-composition-api@0.12.2

npm ERR! code ETARGET
npm ERR! notarget No matching version found for nuxt-composition-api@0.12.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by mathe42** [comment]
Package name changed to @nuxtjs/composition-api

**Comment by Dan503** [comment]
ok yep, after uninstalling `nuxt-composition-api` and then installing `@nuxtjs/composition-api` and replacing references to the old name with the new name, `useAsync()` appears to work as expected when using the native `fetch()` API.

I also don't seem to be having the issues in FF that I was having before. I'll close this issue as fixed. 😃
