### ISSUE TITLE
throwing inside `useFetch` differs from `fetch`

### ISSUE THREAD

**Issue by posva** [nuxt-community/composition-api#185]
**🐛 The bug**

When throwing/rejecting inside of the function passed to `useFetch`

**🛠️ To reproduce**

1. `useFetch(async () => { throw new Error('nope') })`
2. Go to the page where the error should happen

**🌈 Expected behaviour**

I would expect to end up on the error page as if we were calling `ctx.error()`. Or being able to call it and send (during SSR) the error page to avoid a hydration error

**ℹ️ Additional context**

I based my assumption on this https://nuxtjs.org/blog/understanding-how-fetch-works-in-nuxt-2-12/#error-handling

**Comment by danielroe** [comment]
@posva Many thanks for taking the time to file an issue ❤️ 

However, I think this is working as intended. For example, the below code works as expected:
```vue
<template>
  <main>
    <code>{{ JSON.stringify($fetchState) }}</code>
  </main>
</template>

<script>
import { defineComponent, useFetch, useContext } from 'nuxt-composition-api'

export default defineComponent({
  setup() {
    const { res } = useContext()

    useFetch(async () => {
      if (process.server) {
        res.statusCode = 404
      }
      throw new Error('Post not found')
    })
  },
})
</script>
```

The HTTP code is in fact 404:
<details><summary><code>❯ http http://localhost:3000/ --headers</code></summary>

```bash
HTTP/1.1 404 Not Found
Accept-Ranges: none
Connection: keep-alive
Content-Length: 3516
Content-Type: text/html; charset=utf-8
Date: Wed, 05 Aug 2020 14:59:45 GMT
ETag: "dbc-xKrJdjkQc1wvTRBRett+n0bJx/c"
```

</details>

... and a check for `$fetchState.error` returns the error that was thrown.

Precisely the same behaviour occurs when running the following instead:
```vue
<script>
import { defineComponent } from 'nuxt-composition-api'

export default defineComponent({
  async fetch() {
    if (process.server) {
      this.$nuxt.context.res.statusCode = 404
    }
    throw new Error('Post not found')
  },
})
</script>
```

If this differs from your experience, I'd very much appreciate a reproduction 😃

**Comment by posva** [comment]
That version is working well, the problem is when calling `ctx.error` to redirect to the error page. But maybe this is just how it works or it's a bug on `fetch` since it does the same without nuxt-composition-api...

**Comment by danielroe** [comment]
@posva I think both `fetch` and `useFetch` have the same behaviour. And this seems to work fine:
```ts
    const { error, redirect } = useContext()
    useFetch(async () => {
        error('My error')
		// so does this
        // redirect('/meta')
    })
```

Can you share your code? I wonder if it is about timing - so maybe my tests here are working fine but an error thrown further along in the `serverPrefetch` lifecycle isn't properly redirecting to the error page?

**Comment by posva** [comment]
Here you go https://github.com/posva/nuxt-composition-api-185
Go to http://localhost:3001/ and you will see a client hydration error. If using `fetch`, there isn't any

**Comment by danielroe** [comment]
I think the difference is actually between new and old fetch (it is the old fetch version in the repro). See https://github.com/nuxt/nuxt.js/issues/8092.

**Comment by posva** [comment]
Ok, thanks! Good to know the behavior changed! thanks for the links too 🙂

**Comment by danielroe** [comment]
@posva Sorry for the long delay in addressing!
