### ISSUE TITLE
help: eslint error by importing 'PropType'

### ISSUE THREAD

**Issue by qhantom** [nuxt-community/composition-api#189]
I would like to import `PropType` from `nuxt-composition-api` module. According to the source code, `nuxt-composition-api `exposes `@vue/composition-api` so that I can use `PropType` without any issues. As far as I see, no error is generated technically but ESLint confuses me here:

![image](https://user-images.githubusercontent.com/54100938/89576542-b7fb8c80-d82f-11ea-8674-d80ce28e956b.png)

Is it just a linting bug or is there anything configured wrongly?

Thanks and happy coding!

**Comment by danielroe** [comment]
@qhantom This is a known issue with that particular rule in eslint and TypeScript code, and is not particular to this project.

I'd recommend ensuring you have eslint set up with the correct parse (see [Nuxt recommended config](https://typescript.nuxtjs.org/guide/lint.html#configuration)), turning the rule off for TypeScript code (as there is another TypeScript eslint rule) or doing an explicit type import (`import type { PropType } ...`).

Some background:
 - https://github.com/eslint/typescript-eslint-parser/issues/416
 - https://github.com/typescript-eslint/typescript-eslint/issues/131

**Comment by silverbackdan** [comment]
This issue appeared again for me today after an npm dependency upgrade.

The fix to explicitly import `PropType` as a `type` using `import type { PropType } from 'vue'` still works.
