### ISSUE TITLE
fix: [Vue warn]: Write operation failed: computed value is readonly.

### ISSUE THREAD

**Issue by danielroe** [nuxt-community/composition-api#19]
**🐛 The bug**
At the moment, if a component that calls `useFetch` has a computed property returned from setup, it will give the following error:
```
[Vue warn]: Computed property was assigned to but it has no setter.
```

It still works correctly, but this is unattractive, and ideally we wouldn't be attempting to assign a value to a computed property at all.

**Comment by mathe42** [comment]
In Vue3 the computed ref has an property effect normal ref don't have this property. Maybe we get / have something like this in @vue/composition-api

**Comment by mathe42** [comment]
Nope with @vue/composition-api computed and ref look the same...

**Comment by mathe42** [comment]
We can export a modifyed computed:

```js
const computed = (...args) => {
  const _c = oldComputed(...args)
  _c.__v__computed = true
  return _c
}

```

**Comment by mathe42** [comment]
see https://github.com/vuejs/composition-api/issues/445

**Comment by mathe42** [comment]
https://github.com/nuxt-community/composition-api/blob/main/src/fetch.ts#L263 Can we just add check if `isReadonly(vm[key])` ?

**Comment by danielroe** [comment]
Definitely worth a test.

**Comment by danielroe** [comment]
**Update**: after a quick test, we still can't detect readonly properties, once applied to the Vue instance.

**Comment by TheNoim** [comment]
Is there a good workaround?

**Comment by chovyprognos** [comment]
how do i create a setter?

**Comment by develth** [comment]
When using a vuex component that is computed and gets called in useFetch, there is an vuex Error:

`do not mutate vuex store state outside mutation handlers.`

Sad, that this can´t be ignored

**Comment by QuentinLeCaignec** [comment]
I'm getting this same warning but it's not even a computed variable.

`const page: any = reactive({
      content: null,
    })`

later :
`const { fetch } = useFetch(async () => {
      const pageData = await (fetch stuff...)
      if (pageData) {
         page.content = pageData
      }
    })`

Is there any way to avoid this weird warning?

**Comment by LCseniordev** [comment]
Hi, I'm facing the same issue with:
```
"nuxt": "^2.15.8",
"@nuxtjs/composition-api": "^0.33.1",
```
If there is any update on how to fix that?

**Comment by Daewon25** [comment]
Hi same here. 
Any updates?

**Comment by bensinca** [comment]
Samsies 

```
 "nuxt": "^2.15.8",
 "@nuxtjs/composition-api": "^0.31.0",
 ```

**Comment by SebbeJohansson** [comment]
@danielroe any news on this?

**Comment by danielroe** [comment]
Please do open a new issue with a reproduction and I'll be very happy to look into it. 🙏

**Comment by SebbeJohansson** [comment]
I'll make sure to make an issue with a reproduction!

**Comment by broox** [comment]
just because this is the top search result for this error. i ran into this issue when i accidentally had a `ref` attribute in my template that was named the same as a computed property. renaming/removing the `ref` fixed things up for me.

**Comment by andreiculda** [comment]
> just because this is the top search result for this error. i ran into this issue when i accidentally had a `ref` attribute in my template that was named the same as a computed property. renaming/removing the `ref` fixed things up for me.

This was the case for me. Thanks.
