### ISSUE TITLE
chore: move to nuxt-community

### ISSUE THREAD

**Issue by danielroe** [nuxt-community/composition-api#191]
- [x] using module template
- [x] github invitation
  - [x] approve
- [x] npm invitation
  - [x] approve
  - [x] assign team for
- [x] publish docs as `composition-api.nuxtjs.org`
- [x] update references from `nuxt-composition-api` to `@nuxtjs/composition-api`
- [x] publish initial version of new package
- [x] deprecate `nuxt-composition-api`

**Comment by pi0** [comment]
@danielroe Do you mind adding [netlify.toml](https://github.com/nuxt-community/pwa-module/blob/450507571efab5c414dea3ca633200e7ed5ae316/netlify.toml) file?
