### ISSUE TITLE
docs: How to access router (not route)

### ISSUE THREAD

**Issue by TimoStolz** [nuxt-community/composition-api#198]
I want to access the nuxt router. I try this by doing `const { router } = useContext()`, but to no avail.

**🔍 Where should you find it?**
Probably on the useContext page?

**Comment by danielroe** [comment]
In the Nuxt context, the `router` is within `app`. So, for example:

```ts
const { app: { router } } = useContext()
```

**Comment by TimoStolz** [comment]
Thank you very much!!
