### ISSUE TITLE
Is this a spam, adware or what?

### ISSUE THREAD

**Issue by szvest** [nuxt-community/composition-api#206]
Playing around with the [codesandbox example](https://codesandbox.io/s/github/nuxt-community/composition-api/tree/main/example) I noticed this extra network load/response that looks like a spam/adware. I have no idea from where it is coming from. I tested it locally and got the same. Would it be coming from any particular dependency? 

![nuxt-composition-api-example-codesandbox](https://user-images.githubusercontent.com/1672789/90309231-ab85cc80-dede-11ea-8618-1d492e3febed.gif)

**Comment by danielroe** [comment]
That's an open API with dummy data to populate the post author.
