### ISSUE TITLE
fix: TS2307: Cannot find module '@nuxtjs/composition-api' or its corresponding type declarations.

### ISSUE THREAD

**Issue by jessielaf** [nuxt-community/composition-api#215]
**🐛 The bug**
When I use this package corresponding with vue typescript it does not work.

**🛠️ To reproduce**

1. Create new nuxt project
2. Select typescript
3. Install this package
4. Use this package

**🌈 Expected behaviour**
No error. Everything works as usual

**ℹ️ Additional context**
With the vue composition API package it works with typescript but this one does not.

**Comment by danielroe** [comment]
@jessielaf I can't reproduce with a new project. Are you following the [instructions in the docs](https://composition-api.nuxtjs.org/setup#quick-start)? If so, would you mind creating a repro on GitHub or CodeSandbox?

**Comment by jessielaf** [comment]
I am sorry. It seems that my webstorm was just complaining. When I restarted it was all okay. Sorry for the confusion

**Comment by danielroe** [comment]
No problem!
