### ISSUE TITLE
fix: WARN  Cannot stringify POJOs with symbolic keys Symbol(composition-api.reactiveIdentifier)

### ISSUE THREAD

**Issue by nvitaterna** [nuxt-community/composition-api#216]
**🐛 The bug**
Getting the following warning:
`WARN  Cannot stringify POJOs with symbolic keys Symbol(composition-api.reactiveIdentifier)`

**🛠️ To reproduce**
https://codesandbox.io/s/nuxt-pojo-warning-owp5n

Clicking on 404 doesn't give the error, but refreshing the page on the /404 route does.

**🌈 Expected behaviour**
Not to get the warning :)

**ℹ️ Additional context**
Seems to be coming from the NuxtError object that is applied to custom error pages (https://nuxtjs.org/guide/views/#error-page). Only happens when a setup function is givin (if you remove the setup function from the example it does not give you the warning). This may occur in other places as well but I am starting a new project so I haven't ran into it anywhere else yet.

**Comment by danielroe** [comment]
`ref` and `reactive` objects also have a symbolic key added by the Composition API. This can't be serialized by `devalue` when being passed from server-side render via `window.__NUXT__`, so instead it is stripped out. This warning is just telling you that. It might be possible for `@nuxtjs/composition-api` to strip them out instead, but it would duplicate the work of the serializer and potentially decrease performance. So although it is unattractive to see the warning, my current belief is that it is an acceptable level of annoyance 😃

However - PRs welcome if you can find a performant way to remove the warning.

**Note**: I don't get the error on your CSB when refreshing the `/404` route, so it's possible it's not an issue with the NuxtError object. My money would be on something like `ssrRef` or anything that serializes data on SSR (like `useAsync` or `useFetch`).
