### ISSUE TITLE
Q: How can I use useAsync to return complex object

### ISSUE THREAD

**Issue by ChristophePetitjeanAi3** [nuxt-community/composition-api#224]
How can a useAsync return multiple object ?
I mean, I want this sort of things:
``` ts
const { profil, profilId } = useAsync(async () => {
    let profilId = null as string | null
    let profil = null as ProfilDto | null

    if (params.value.id !== 'create') {
      profilId = params.value.id
      profil = await $axios.$get('/api/profils/' + params.value.id)
    } else {
      profilId = null
      profil = {}
    }

    return {
      profil,
      profilId
    }
  })
```

So that i can use it like this:
![image](https://user-images.githubusercontent.com/70267651/91656151-b16ed680-eab6-11ea-9e6b-ed45eab0e1f0.png)

but I get : 
![image](https://user-images.githubusercontent.com/70267651/91656093-22fa5500-eab6-11ea-8a87-33df54a86b76.png)

**Comment by danielroe** [comment]
@ChristophePetitjeanAi3 It returns a `ref` so you just access it like so:

```js
const val = useAsync(() => //...
// Accessible here
val.value.profil
```

If you need standalone reactive values you could create computed properties, for example.

**Comment by ChristophePetitjeanAi3** [comment]
I will later edit parts af returned values from API for edit forms.
So I created a data via

``` ts
import { useAsync, useContext, ref } from '@nuxtjs/composition-api'
import { ProfilDto } from '../models/ResponsesTypes'

export default function useDetailedProfils () {
  const { $axios, params, $notification, $router, $dialog } = useContext()
  const loading = ref(false)
  const asyncDatas = useAsync(async () => {
    let profilId = null as string | null
    let profil: ProfilDto
...
    return {
      profil,
      profilId
    }
  })

  const profil = ref(asyncDatas.value?.profil ?? {})
  const profilId = ref(asyncDatas.value?.profilId ?? null)

  const save = async () => {
 ...
  }

  const remove = async () => {
  ...
  }

  return { profil, profilId, loading, save, remove }
}
```
then in my component:
``` ts
import { defineComponent, useMeta } from '@nuxtjs/composition-api'
import useProfilDetail from '@/use/use-profil-detail'

export default defineComponent({
  head: {},
  setup () {
    const { profil, profilId, save, remove, loading } = useProfilDetail()

    useMeta({ title: profilId.value ? 'edit': 'create' })

    console.log(profilId.value)

    return { profil, profilId, save, remove, loading }
  },
})
```

In the console i see the correct profilId whereas the meta is wrong....

**Comment by danielroe** [comment]
Yes, the issue is it should be computed rather than ref, so it will automatically update:
```js
  const profil = computed(() => asyncDatas.value?.profil ?? {})
  const profilId = computed(() => asyncDatas.value?.profilId ?? null)
```

**Comment by ChristophePetitjeanAi3** [comment]
Yes, I got it to work like this:

use-profil-ts:
``` ts
import { useAsync, useContext, ref } from '@nuxtjs/composition-api'
import { ProfilDto } from '../models/ResponsesTypes'

export default function useDetailedProfils () {
  const { $axios, params, $notification, $router, $dialog } = useContext()
  const loading = ref(false)

  const asyncDatas = useAsync(async () => {
    let profil = {} as ProfilDto
    let profilId = null as string | null
...
    return {
      profil,
      profilId
    }
  })

  const save = async () => {
    loading.value = true
    if (asyncDatas.value?.profilId != null) {
...
    } else {
...
  }

  const remove = async () => {
...
  }

  return { loading, save, remove, asyncDatas }
}

```

component.vue:
``` vue
<template>
  <v-card v-if="asyncDatas && asyncDatas.profil" :loading="loading" class="profilEditCreate">
...
  </v-card>
</template>

<script lang="ts">
import { defineComponent, useMeta } from '@nuxtjs/composition-api'
import useProfilDetail from '@/use/use-profil-detail'

export default defineComponent({
  head: {},
  setup () {
    const { save, remove, loading, asyncDatas } = useProfilDetail()

    const title = asyncDatas.value?.profilId ? 'Edition de profil' : 'Création de profil'

    useMeta({ title })

    return { save, remove, loading, asyncDatas }
  },

  transition (_to, from) {
    if (!from) { return '' }
    if (from.name === 'administration-profils') { return 'slide-x-transition' }
    return ''
  }
})
</script>
<style scoped lang="scss">
...
</style>

```

Note here that we must use `asynDatas` everywhere. (Especially the one on the v-card, if i remove it, it will fail to load with null ref exception)

It would be much better to get an array of `Ref`.

I think that a `defineSetup()` method would be nice.
This method would allow us to create our `asyndata` method and every special aspect of nuxt plus a standard `setup `method which is augmented with the return of the `asyncData` methods.
Something like:

``` ts
export default defineSetup(()=> {
  asyncData: async ({ $axios, params }: Context) => {
    let profil = {} as ProfilDto
    let profilId = null as string | null
// ....
    return {
      profil,
      profilId
    }
  },

  setup() {
    const loading = ref(false)
    const save = async () => {
      loading.value = true
      if (profilId.value != null) {
// .....
      }
      loading.value = false
    }
  
    const remove = async () => {
// ......
    }
  }

}
```
It would be Epic and you wouldn't have to overrides all new nuxt things.

I do not know if I'm clear enough... (English is not my natal language)

**Comment by danielroe** [comment]
@ChristophePetitjeanAi3 Glad things are working!

I do understand your proposal - but I wonder if there is another approach. Nuxt calls `asyncData` outside the component lifecycle, which complicates it slightly.

Tagging @mathe42 in case he has any ideas.

**Comment by Mikaleb** [comment]
> Yes, the issue is it should be computed rather than ref, so it will automatically update:
> 
> ```js
>   const profil = computed(() => asyncDatas.value?.profil ?? {})
>   const profilId = computed(() => asyncDatas.value?.profilId ?? null)
> ```
> 
> Note that unlike asyncData, `useAsync` returns a ref that _starts out null_ and will take a moment until it resolves to the correct value, so you will need (as you have done) to handle the period when it is just null. So in your code:
> 
> ```js
>   setup() {
>     // ...
>     useMeta({ title: profilId.value ? 'edit': 'create' })
>     // ...
> ```
> 
> `profilId.value` might well still be `null` when `useMeta` is called.

I was checking on that and unfortunately, profilId.value is always null therefore always return create, I can pull my own code to show there if needed but it's quasi an exact copy of what ChristophePetitjeanAi3 did.

Is there any solution into it ?

**Comment by ThaddeusJiang** [comment]
[Help]

https://composition-api.nuxtjs.org/helpers/usemeta/

```
 // You can even pass a function to achieve a computed meta
    const message = ref('')
    useMeta(() => ({ title: message.value }))
```

the title still is '' after `fetch data`, How to solve it?
