### ISSUE TITLE
Vue Composition API v1.0.0-beta.14 breaks package

### ISSUE THREAD

**Issue by aaronhuisinga** [nuxt-community/composition-api#238]
**🐛 The bug**
The new release of Vue Composition API (v1.0.0-beta.14) breaks this package. The new release removes the markReactive export (https://github.com/vuejs/composition-api/pull/512), which the Nuxt Composition API currently depends on.

When attempting to compile our Nuxt app after updating the Vue Composition API, we get the following error:

```
 ✖ Nuxt Fatal Error                                                                                                │
   │                                                                                                                     │
   │   SyntaxError: The requested module                                                                                 │
   │   'file:///Users/xxx/Documents/code/xxx/client/node_modules/@vue/composition-api/index.js' does not   │
   │   provide an export named 'markReactive'    
```

**🛠️ To reproduce**

1. Update Vue Composition package to v1.0.0-beta.14
2. Run yarn dev

**Comment by JamieCurnow** [comment]
If anyone is looking for a workaround until this is fixed, add a resolution to your package.json for @vue/composition-api:
```
"resolutions": {
    "@vue/composition-api": "1.0.0-beta.13"
  }
```

**Comment by liaojunhong** [comment]
This is because the 1.0.0-beta.14 version of vue-composition-api has been updated and markReactive has been removed
