### ISSUE TITLE
[vue-composition-api] already installed. Vue.use(VueCompositionAPI) should be called only once.

### ISSUE THREAD

**Issue by GaborTorma** [nuxt-community/composition-api#241]
**🐛 The bug**
I get the following message when i use `"@vue/composition-api": "=1.0.0-beta.14"` and `"@nuxtjs/composition-api": "=0.12.4"`:
`[vue-composition-api] already installed. Vue.use(VueCompositionAPI) should be called only once.`

![2020-09-17_7-44-06](https://user-images.githubusercontent.com/11255009/93425141-ab039b80-f8b9-11ea-8df9-acfde9700da1.png)

**Comment by danielroe** [comment]
@GaborTorma This error means you have two versions of the `@vue/composition-api` installed. At the moment Nuxt composition API still depends on beta 13 - so you can get around this by adjusting the version to beta 13 in your package.json.

**Comment by wikak** [comment]
I have this issue. Even if i change the version of @vue/composition-api to beta 13

**Comment by mathe42** [comment]
Do you have a `Vue.use(VueCompositionAPI)` in your own code?

**Comment by wikak** [comment]
> Do you have a `Vue.use(VueCompositionAPI)` in your own code?

No. I should ?

**Comment by mathe42** [comment]
Nope :D

**Comment by wikak** [comment]
> Nope :D

`"dependencies": {
    ...
    "@nuxtjs/composition-api": "^0.12.5",
    "@vue/composition-api": "1.0.0-beta.14",
  },`
My package.json file

**Comment by mathe42** [comment]
Try removing the node_modules folder and yarn.lock or the npm lock file. And install all deps again.

**Comment by wikak** [comment]
> Try removing the node_modules folder and yarn.lock or the npm lock file. And install all deps again.

Nice, it works great thanks @mathe42

**Comment by wikak** [comment]
> > Try removing the node_modules folder and yarn.lock or the npm lock file. And install all deps again.
> 
> Nice, it works great thanks @mathe42.
