### ISSUE TITLE
fix: Error in useAsync inside setup

### ISSUE THREAD

**Issue by hobbsi** [nuxt-community/composition-api#247]
**🐛 The bug**
When running code from example https://composition-api.nuxtjs.org/useAsync got 
"TypeError Converting circular structure to JSON"

**🛠️ To reproduce**
Create a Nuxt project, add composition-api and try to run code example from https://composition-api.nuxtjs.org/useAsync 

TypeError
Converting circular structure to JSON

.nuxt/composition-api/index.js:33:
sanitise
.nuxt/composition-api/index.js:92:
RefImpl.set [as value]
.nuxt/composition-api/index.js:215:
Object
internal/process/next_tick.js:68:7
process._tickCallback

**Comment by danielroe** [comment]
You're right, the whole axios response can't be serialised. Instead, you should use something like:
```js
    const posts = useAsync(async () => {
      const { data } = await axios.get(
        'https://jsonplaceholder.typicode.com/todos/1'
      )
      return data
    })
```
