### ISSUE TITLE
fix: jest test reports error when encountering `useContext`

### ISSUE THREAD

**Issue by yeefun** [nuxt-community/composition-api#248]
### 🐛 The bug

I use Jest tests, but it seems to report error when it encounters `useContext`.

<img width="998" alt="截圖 2020-09-23 18 20 51" src="https://user-images.githubusercontent.com/32699979/94000269-87fd4e00-fdc9-11ea-9238-50e981250b25.png">

I log `vm[globalNuxt]` at `@nuxtjs/composition-api/lib/cjs/entrypoint.js` and find it is `undefined`.

<img width="769" alt="截圖 2020-09-23 18 33 17" src="https://user-images.githubusercontent.com/32699979/94001574-44a3df00-fdcb-11ea-82a6-eb2a268a26eb.png">

### To reproduce

1. Go to https://github.com/yeefun/mirror-media-nuxt/
2. Clone this repo by `git clone -b chore/bug --single-branch https://github.com/yeefun/mirror-media-nuxt.git`
3. `yarn install`, then `yarn test components/__tests__/UIStoryBody.spec.js`

**Comment by bissolli** [comment]
Guys, any idea on what might be causing this issue? I am also facing it and could not figure out how to solve that.

**Comment by danielroe** [comment]
The issue here is that `this.$nuxt` doesn't exist in your Jest context - you will need to either declare the appropriate properties globally or on a `localVue`, e.g.:
```ts
Vue.prototype.$nuxt = {
  context: {
    // whatever you need to mock/stub
  },
}
```

**Comment by huntz20** [comment]
> The issue here is that `this.$nuxt` doesn't exist in your Jest context - you will need to either declare the appropriate properties globally or on a `localVue`, e.g.:
> 
> ```ts
> Vue.prototype.$nuxt = {
>   context: {
>     // whatever you need to mock/stub
>   },
> }
> ```

@danielroe hei daniel can you please give more information or article  to make me more clear about this issue 

thanks

**Comment by yeefun** [comment]
@huntz20

Example:

XXX.vue

```javascript
import { useContext } from '@nuxtjs/composition-api'

export default {
  name: 'XXX',
  setup() {
    const { store } = useContext()

    // ...
  },
}
```

XXX.spec.js

```javascript
import { shallowMount } from '@vue/test-utils'
import XXX from '../XXX.vue'

test('xxx', () => {
  const wrapper = shallowMount(XXX, {
    mocks: {
      $nuxt: {
        context: {
          store: { /* ... */ },
        },
      },
    },
  })

  // ...
})
```

I hope this will help.

**Comment by hogeihogemi** [comment]
@danielroe Hi danielroe

I tried below with reference to https://github.com/nuxt-community/composition-api/issues/248#issuecomment-745811138
(I tried also this method. but same result) https://github.com/nuxt-community/composition-api/issues/248#issuecomment-702303960 

but an error has occurred
```
[Vue warn]: Error in data(): "TypeError: Cannot read property 'params' of undefined"
TypeError: Cannot read property 'params' of undefined
```



XXX.vue
```javascript
import { useContext } from '@nuxtjs/composition-api'

export default {
  name: 'XXX',
  setup() {
    const { route} = useContext()
    console.log(route.params) // undefind
    console.log(route.value.params.id)  // TypeError: Cannot read property 'params' of undefined

    // ...
  },
}
```

XXX.spec.js
```javascript
import { shallowMount } from '@vue/test-utils'
import XXX from '../XXX.vue'

test('xxx', () => {
  const wrapper = shallowMount(XXX, {
      mocks: {
        $nuxt: {
          context: {
            route: {
              params: {
                id: 1,
              },
            },
          },
        },
      },
    })

  // ...
})
```

I use verion
```
    "@nuxtjs/composition-api": "^0.19.1",
    "nuxt": "^2.14.12",
    "@vue/test-utils": "^1.1.2",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "^26.6.3",
    "jest": "^26.6.3",
    "vue-jest": "^3.0.4"
```

Is there anything I can fix?

thank you

**Comment by danielroe** [comment]
`route`, `query`, `from` and `params` are taken from the `$route` object rather than the Nuxt context so they need to be mocked differently:
```js
import { shallowMount } from '@vue/test-utils'
import XXX from '../XXX.vue'

test('xxx', () => {
  const wrapper = shallowMount(XXX, {
    mocks: {
      $route: {
        params: {
          id: 1,
        },
      },
    },
  })

  // ...
})
```

**Comment by wesley-spencer** [comment]
@danielroe can you please explain to me what I am doing wrong?
`import component from "@/components/caseAssignment/component.vue"
import { shallowMount } from "@vue/test-utils"

test("xxx", () => {
  const wrapper = shallowMount(component, {
    mocks: {
      $nuxt: {
        context: {
          $axios: {
            post: () => new Promise.resolve({ data: null }),
          },
        },
      },
    },
  })
  expect(wrapper.text()).toMatch("Staff Metrics")
})`

Error
`Test suite failed to run

    This must be called within a setup function.

      58 | import { useContext } from "@nuxtjs/composition-api"
      59 |
    > 60 | const { $axios, $toast } = useContext()
         | ^
      61 | const emit = defineEmits(["input"])
      62 |
      63 | const props = defineProps({

      at useContext (node_modules/@nuxtjs/composition-api/dist/runtime/index.js:246:18)`

**Comment by wesley-spencer** [comment]
@danielroe Can you please explain what I am doing wrong here?
`import component from "@/components/caseAssignment/component.vue"
import { shallowMount } from "@vue/test-utils"

test("xxx", () => {
  const wrapper = shallowMount(component, {
    mocks: {
      $nuxt: {
        context: {
          $axios: {
            post: () => new Promise.resolve({ data: null }),
          },
        },
      },
    },
  })
  expect(wrapper.text()).toMatch("Staff Metrics")
})
Test suite failed to run

    This must be called within a setup function.

      58 | import { useContext } from "@nuxtjs/composition-api"
      59 |
    > 60 | const { $axios, $toast } = useContext()
         | ^
      61 | const emit = defineEmits(["input"])
      62 |
      63 | const props = defineProps({

      at useContext (node_modules/@nuxtjs/composition-api/dist/runtime/index.js:246:18)`
