### ISSUE TITLE
feat: Force update reactive value by useAsync, when its component remounted.

### ISSUE THREAD

**Issue by tnkgs** [nuxt-community/composition-api#253]
**🆒 Your use case**

Now, ` useAsync` hydrate reactive values from ssr.
If reactive values wasn't hydrated from ssr (In case its component is mounted by vue-router for the first time), it hydrated by client side setup function. But, when its component remounted for the second time,  it is not updated by `useAsync`.

I need update ssrRef value when remounted.
so, I'm both using `useAsync` and `onMounted`.
```ts
const id = params.value['id']
const data = useAsync(async () => {
  return await fetchSomeData(id)
})
onMounted(async () => {
  if (!data.value || data.value.id !== id) {
    data.value = await fetchSomeData(id)
  }
})
```
it's verbose a little.

**🆕 The solution you'd like**

In the case of it mounted after the second time, I propose `useAsync`  force update ssrRef.

**Comment by tnkgs** [comment]
> just pass a key as the scond argument to useAsync (for example route.fullPath ).

I see, that seems to be enough.
Thank you.

**Comment by mathe42** [comment]
When I have time I will add this to the docs...
