### ISSUE TITLE
fix: route ref does not update for more then twice

### ISSUE THREAD

**Issue by gotenxds** [nuxt-community/composition-api#256]
**🐛 The bug**
What isn't working? Describe what the bug is.
When using useContext to track the route, the route object stops updating after two updates.

To illustrate this I create a setInterval function that prints both 
`route.value.path`
and 
`$nuxt._route.path`

```ts
  const { route } = useContext()

  setInterval(() => {
    // eslint-disable-next-line no-console
    console.log(route.value.path)
    // eslint-disable-next-line no-undef
    console.log(`$nuxt: ${$nuxt._route.path}`)
  }, 5000)
```

You would expect the same value, lets see: 

![image](https://user-images.githubusercontent.com/3519520/95642376-d6d90200-0ab0-11eb-945d-bdbe7ad81e3f.png)

We can see in the log output 3 ticks of 2 prints
the first two ticks behave as expected, in the last tick the route ref does not update

**🛠️ To reproduce**

as described above

I'd be very grateful for a link to a gist or repo that reproduces the bug.

**🌈 Expected behaviour**
route ref to update continuously

**Comment by danielroe** [comment]
@gotenxds I wonder if this is also related to https://github.com/nuxt/nuxt.js/issues/7696 with pending fix https://github.com/nuxt/nuxt.js/pull/8170

**Comment by danielroe** [comment]
I'm closing this but you're welcome to provide more information and I'll happily look into it.
