### ISSUE TITLE
fix: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by aaronhuisinga** [nuxt-community/composition-api#263]
**🐛 The bug**
After updating from v0.12.5 to v0.12.6+, we are frequently seeing "RangeError: Maximum call stack size exceeded" when viewing different pages. The only code change was updating this package, everything else is exactly as it was before. Reverting to v0.12.5 fixes this issue, which seems to be present on both v0.12.6 and v0.13.0.

**🛠️ To reproduce**
I will try and throw together something that can reproduce this later today. I'm not certain if this was something in the Vue Composition API package or in this package that results in the issue.

**🌈 Expected behaviour**
The page should render without any errors. Instead we're seeing this RangeError and the Nuxt error page.

**ℹ️ Additional context**
```
RangeError: Maximum call stack size exceeded
    at Proxy.reactiveGetter (vue.runtime.esm.js?2b0e:1024)
    at Proxy.reactiveGetter (vue.runtime.esm.js?2b0e:1025)
    at Proxy.reactiveGetter (vue.runtime.esm.js?2b0e:1025)
    at Proxy.reactiveGetter (vue.runtime.esm.js?2b0e:1025)
    at Proxy.reactiveGetter (vue.runtime.esm.js?2b0e:1025)
    at Proxy.reactiveGetter (vue.runtime.esm.js?2b0e:1025)
    at Proxy.reactiveGetter (vue.runtime.esm.js?2b0e:1025)
    at Proxy.reactiveGetter (vue.runtime.esm.js?2b0e:1025)
    at Proxy.reactiveGetter (vue.runtime.esm.js?2b0e:1025)
    at Proxy.reactiveGetter (vue.runtime.esm.js?2b0e:1025)
```

**Comment by danielroe** [comment]
@aaronhuisinga Thanks for the heads-up. I'll look forward to seeing a reproduction :+1:

**Comment by aaronhuisinga** [comment]
@danielroe I've figured out the cause here! Returning the router from the setup method will cause the issue. We are using the router method in our template for pushing routes programatically. This causes the loop and the exception.

```ts
<script lang="ts">
import { defineComponent, useContext } from '@nuxtjs/composition-api';

export default defineComponent({
  setup() {
    const {
      app: { router },
    } = useContext();

    return { router };
  },
});
</script>
```

**Comment by danielroe** [comment]
@aaronhuisinga This is replicable without `@nuxtjs/composition-api`. I'd suggest raising an issue on `@vue/composition-api` as I suspect the change you noticed is due to a change upstream. Here's a CSB reproduction: https://codesandbox.io/s/inspiring-easley-e6zmo?file=/nuxt.config.js . Note that it's not an issue of Nuxt context - even exposing `vm.$router` causes the same issue.
