### ISSUE TITLE
help: Why my ssrRef with typeof Array couldn't update automaticly?

### ISSUE THREAD

**Issue by JanusSpark** [nuxt-community/composition-api#282]
I'm trying to update my array data after onMounted,because I have some information will get on client side,but It isn't update automaticly.

js scroll
```
function processScrollerListSync(list: any) {
  ....
  return newList;
}
async function processScrollerListAsync(list: any) {
  // add followStatus prop for each item
  ....
  return newList;
}

const scrollList = ssrRef(processScrollerListSync(props.list));

onMounted(async () => {
        const newList = await processScrollerListAsync(scrollList.value, queryFollow.value);
        scrollList.value = newList;
    });

```

template scroller
```
<scrollerItem
        v-for="(item, index) in scrollList"
        :key="`${index}${item.itemId}`"
        :item="item"
      ></scrollerItem>
```
template scrollerItem
```
<template>
  <li >
    <div v-else class="txt">{{ item.cms_data.title }}-{{ item.followStatus }}-{{ test }}--{{ test2 }}</div>
  </li>
</template>
```
js scrollerItem
```

export default defineComponent({
  props: {
    item: {
      type: Object as PropType<any>,
      requier: true,
    },
  },
  setup(props, context) {
    const test = computed(() => props.item?.followStatus === 1);
    const test2 = computed(() => props.item?.followStatus);
    return {
      test,
      test2,
    };
  },
});
</script>
```

When I tried to use the value in scrollList to render my template,I found that it wasn't updated anymore.
When I watch the data in Vue devtools props.item?.followStatus has update right now,but my template not update.

After `scrollList.value = newList;`
props.item?.followStatus only change in vue devtools not on template.
test and test2 not change;

After `scrollList.value = scrollList.value.concat(1)`

The template and data in vue devtools will update immediately.

What should I do , if I only want to update item in Array??

**Comment by JanusSpark** [comment]
I resove the problem by split the value which I want to add in item of scrollList to another new array.

**Comment by danielroe** [comment]
@JanusSpark I believe the issue you are experiencing is a more general issue with how the composition API plugin for Vue 2 works. (Note for instance these caveats - https://github.com/vuejs/composition-api#limitations.)

You are welcome to raise an issue in that repo, or I'd be happy to look at a code reproduction - for example, on https://template.nuxtjs.org/
