### ISSUE TITLE
fix: "export 'globalPlugin' was not found in '@nuxtjs/composition-api'

### ISSUE THREAD

**Issue by gd4Ark** [nuxt-community/composition-api#286]
**🐛 The bug**
```bash
 WARN  Compiled with 1 warnings                                                                                                                            friendly-errors 10:32:56


 WARN  in ./.nuxt/composition-api/plugin.js                                                                                                                friendly-errors 10:32:56

"export 'globalPlugin' was not found in '@nuxtjs/composition-api'
```

It's just a warning, but the page keeps loading

![image](https://user-images.githubusercontent.com/27952659/97945206-c0794a00-1dc1-11eb-8e7a-edffc53327ff.png)

**🛠️ To reproduce**

[getting-started](https://composition-api.nuxtjs.org/getting-started/setup)

1. install @nuxt/composition-api
2. edit nuxt.config.js buildModule
3. yarn dev

**🌈 Expected behaviour**
make it work

**ℹ️ Additional context**
version:
- @nuxt/typescript-build@2.0.3
- nuxt@2.11.0
- vue@2.6.11
- @nuxtjs/composition-api@0.14.0

I tried downgrading to v0.13.0, but the problem remains the same

**Comment by danielroe** [comment]
@gd4Ark Could you reproduce that on https://template.nuxtjs.org? That would be really helpful.

**Comment by gd4Ark** [comment]
@danielroe 
Surprisingly I can't reproduce this issue in codesandbox, I'm not sure if this issue is due to `@nuxtjs/composition-api` itself, I'll put the source code that can reproduce it [here](https://github.com/fa-web-template/nuxt-app-demo).
Basically, I got this source code by doing the following.
```bash
npx @femessage/create-nuxt-app nuxt-app-demo -t admin
yarn add @nuxtjs/composition-api
```
nuxt.config.js
```diff
+ buildModules: [
+ '@nuxtjs/composition-api'
+ ]
```
I'm actually one of the maintainers of the @femessage/create-nuxt-app.

Best regards.

**Comment by danielroe** [comment]
@gd4Ark It looks like upgrading Nuxt would solve the issue for you (you are using 2.11).

**Comment by gd4Ark** [comment]
@danielroe 
Upgrade to nuxt@2.14.7 and make it work, uplifting!

PS: The [documentation](https://composition-api.nuxtjs.org/) does not mention that a low version of Nuxt can cause this problem

**Comment by danielroe** [comment]
@gd4Ark To tell you the truth, I'm not sure *why* there was an issue with 2.11 - but yes, it would be good to mention it in the docs.

**Comment by gd4Ark** [comment]
In the end I found that the problem had nothing to do with the Nuxt version, and that the real reason seemed to be that I needed to add the following configuration to `nuxt.config.js`:
```js
build: {
    babel: {
      presets({ isServer }) {
        return [
          [
            require.resolve('@nuxt/babel-preset-app'),
            {
              corejs: { version: 3 },
              targets: isServer
                ? {
                    node: 'current',
                  }
                : {
                    ie: 11,
                    chrome: 57,
                  },
            },
          ],
        ]
      },
    },
}
```

This also works at Nuxt@2.11.0

**Comment by danielroe** [comment]
@gd4Ark Do you mean you had to add this to a fresh Nuxt config, or that you had to use this instead of another preset customisation?

**Comment by gd4Ark** [comment]
@gd4Ark I don't know much about this, but when I remove this presets configuration, I will get the above error.

maybe it's because of core-js?
