### ISSUE TITLE
Issue: Cannot find module '@vue/composition-api'

### ISSUE THREAD

**Issue by CrazyUmka** [nuxt-community/composition-api#290]
**🐛 The bug**
If you launch a built application with only production dependencies without dev you will get that error above or I don't understand what it's mean configuration option `buildModules`.

**🛠️ To reproduce**

1. Create simple application via `yarn create nuxt-app`
2. Add devDependencies via `yarn add -D @nuxtjs/composition-api` and add this dependency to *buildModules* in *nuxt.config.js* file
3. Run `yarn build`
4. Clean `node_modules` directory and after that run `NODE_ENV=production yarn`
5. Run `yarn start` and open browser
6. See error

**🌈 Expected behaviour**
Start the application without errors.

**ℹ️ Additional context**
![Error](https://user-images.githubusercontent.com/5736719/98484275-4f052580-221f-11eb-8e5b-3ebf478cdb70.png)
Dockerfile for reproduce problem
```dockerfile
FROM node:latest as builder

WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn

COPY . ./

RUN yarn build

FROM node:alpine

WORKDIR /app
COPY package.json yarn.lock ./

ENV NODE_ENV=production
RUN yarn

COPY nuxt.config.js ./
COPY --from=builder /app/.nuxt ./.nuxt/
COPY --from=builder /app/static ./static/

EXPOSE 3000

ENV NUXT_HOST=0.0.0.0

ENTRYPOINT [ "yarn", "run" ]
CMD [ "start" ]
```

**Comment by danielroe** [comment]
@CrazyUmka You will either need to add `@vue/composition-api` to your `transpile` array in `nuxt.config` or ensure it is installed as a production dependency.
```js
{
  transpile: [/@vue[\\/]composition-api/],
}
```

**Comment by CrazyUmka** [comment]
@danielroe Thanks for your attention! I added option transpile in the build section but it doesn't work. My nuxt.config.js:
```javascript
export default {
  // Global page headers (https://go.nuxtjs.dev/config-head)
  head: {
    titleTemplate: '%s - web',
    title: 'web',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: '' },
    ],
    link: [{ rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }],
  },

  // Global CSS (https://go.nuxtjs.dev/config-css)
  css: [],

  // Plugins to run before rendering page (https://go.nuxtjs.dev/config-plugins)
  plugins: [],

  // Auto import components (https://go.nuxtjs.dev/config-components)
  components: true,

  // Modules for dev and build (recommended) (https://go.nuxtjs.dev/config-modules)
  buildModules: [
    // https://go.nuxtjs.dev/typescript
    '@nuxt/typescript-build',
    // https://go.nuxtjs.dev/stylelint
    '@nuxtjs/stylelint-module',
    // https://composition-api.nuxtjs.org
    '@nuxtjs/composition-api',
  ],

  // Modules (https://go.nuxtjs.dev/config-modules)
  modules: [],

  // Build Configuration (https://go.nuxtjs.dev/config-build)
  build: {
    transpile: [/@nuxtjs[\\/]composition-api/],
  },
}
```

**Comment by danielroe** [comment]
@CrazyUmka It should be the Vue composition API in the transpile array.

**Comment by CrazyUmka** [comment]
> @CrazyUmka It should be the Vue composition API in the transpile array.

I can't understand. What does it mean? Where should I add it? In the nuxtjs documentation wrote this: https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-build#transpile

**Comment by danielroe** [comment]
@CrazyUmka No, you added it in the right place, but you added the wrong thing - see my original comment which was to add the **vue** composition API to the array:

![Screenshot from 2020-11-09 11-44-56](https://user-images.githubusercontent.com/28706372/98537385-17c76080-2281-11eb-82a9-cc5e23bd002b.png)

**Comment by CrazyUmka** [comment]
> @CrazyUmka It should be the Vue composition API in the transpile array.

Thanks, I'll try it today. I saw my mistake 😅

**Comment by CrazyUmka** [comment]
Thanks! It works! Now I understand better 🙏

**Comment by LouisMazel** [comment]
> @CrazyUmka You will either need to add `@vue/composition-api` to your `transpile` array in `nuxt.config` or ensure it is installed as a production dependency.
> 
> ```js
> {
>   transpile: [/@vue[\\/]composition-api/],
> }
> ```

The transpile solution doesn't works for me (`Cannot find module '@vue/composition-api'`) 

And when I manually install `@vue/composition-api@1.0.0-beta.17` (https://github.com/nuxt-community/composition-api/issues/241#issuecomment-693927221 and version founded in requires of `@nuxtjs/composition-api`) I have this error: 

```
[vue-composition-api] already installed. Vue.use(VueCompositionAPI) should be called only once
```

What is the good version of `@vue/composition-api` to install ?

For you information: 
I use **@nuxtjs/composition-api@0.15.0**
With **Typescript (nuxt-ts)** and `Docker image node:14.14.0-alpine3.12`

**Comment by danielroe** [comment]
@LouisMazel Are you manually calling `Vue.use(VueCompositionAPI)`? Could you provide a reproduction?

**Comment by LouisMazel** [comment]
@danielroe Absoluty not for the `Vue.use(VueCompositionAPI)`

You can check this codesandbox: https://codesandbox.io/s/nuxt-ts-forked-tm1v0

**Comment by danielroe** [comment]
@LouisMazel I'll reopen this issue. For now, you can just make sure `@vue/composition-api` (1.0.0-beta.19) is installed in your production dependencies in your `package.json`.

**Comment by LouisMazel** [comment]
Thanks, but when I install 1.0.0-beta.19 I get 
`[vue-composition-api] already installed. Vue.use(VueCompositionAPI) should be called only once`

I keep looking for the problem, I keep you posted

**Comment by LouisMazel** [comment]
It's solved! 

I restarted a new project from scratch (I know...) with `create-nuxt-app`, I setup Typescript and composition-api config, I copied all my files and.. it's works fine. 

No need to install `@vue/composition-api` and no need to set the transpile config

I don't know exactly why, maybe `nuxt@2.4.7` instead of `nuxt@2.4.6` or another version of a package...

**Comment by danielroe** [comment]
@LouisMazel Mysterious ✨ but I'm glad it's sorted!

**Comment by LouisMazel** [comment]
More info: This (my) bug is from docker with the **node:14.14.0-alpine3.12** image. Now I use **node:10**, it's work fine !
So, do not use a alpine version of node

**Comment by CrazyUmka** [comment]
> @danielroe Thank you, but when I install 1.0.0-beta.19 I get
> `[vue-composition-api] already installed. Vue.use(VueCompositionAPI) should be called only once`
> 
> I keep looking for the problem, I keep you informed

@danielroe Hi! I explored the bug which describes above. It's happening when you launch `nuxt dev` if you include  `/@vue[\\/]composition-api/` in transpile array.
