### ISSUE TITLE
fix: useFetch and target mode static still make calls to the API

### ISSUE THREAD

**Issue by nicolashmln** [nuxt-community/composition-api#292]
**🐛 The bug**
When nuxt is generated via the static mode and using `useFetch`, API calls are still made.

**🛠️ To reproduce**

1. Using the example from this repo https://github.com/nuxt-community/composition-api/tree/main/example
2. Execute `npm run generate`
3. Execute `npm run start`
4. Go to http://localhost:8000/ and browse

At the first load, the payload saved is used and no API calls are made. When you click on a link, even though all the `payload.js` are downloaded, nuxt still makes an API call.

**🌈 Expected behaviour**
When you use the `fetch` function in a _normal_ way (eg. not with the composition API), no API calls are made when generated.

**Comment by stigvanbrabant** [comment]
@danielroe i'm still experiencing this issue, is there a specific configuration that needs to be set? i've alread set the target to 'static'. And i am using version ^2.15.8 of nuxt.

**Comment by danielroe** [comment]
Would you create a new issue with a reproduction? 🙏

**Comment by stigvanbrabant** [comment]
Yes i will try to do that tomorrow, i'm actually using the storyblok nuxt module so the useFetch resides inside there.
