### ISSUE TITLE
help: Repository Pattern implemented using plugins with Vuex, Composition API, & TypeScript 

### ISSUE THREAD

**Issue by carlomigueldy** [nuxt-community/composition-api#302]
**📚 What are you trying to do? Please describe.**
I created a Nuxt project and installed @nuxtjs/comopsition-api, @nuxt/typescript and trying to implement Repository pattern using plugins, I created a plugin for the repository and registered it, it works on runtime but all the linting in app I get the errors of the types not recognized by TypeScript. I use `$repositories.userRepository.get()` from inside the **store/index.ts**, but eventually the TypeScript typings does not work.

**🔍 What have you tried?**
![image](https://user-images.githubusercontent.com/45052332/100049984-7f6dd600-2e53-11eb-90ec-69ed315118a8.png)

I have also created a ***.d.ts** that I refer from official docs for Nuxt-TypeScript but still does not work inside the store when I want to call `this.$repositories.userRepository.get()`

![image](https://user-images.githubusercontent.com/45052332/100049625-c60f0080-2e52-11eb-993c-e69b11723f77.png)

When accessing it from a ***.vue** file, the typings work well but I am not sure why the error it's showing up

![image](https://user-images.githubusercontent.com/45052332/100049969-741aaa80-2e53-11eb-92a7-04860c3e6084.png)

**ℹ️ Additional context**
I would appreciate it if you could help me with what I am trying to achieve, here is my [repository](https://github.com/carlomigueldy/nuxt-ts-composition-api-boilerplate) for this project that I am learning Nuxt with Composition API and TypeScript altogether because they seem like a good combo.

You can open a PR if you have a solution. Thank you!

**Comment by danielroe** [comment]
@carlomigueldy I would suggest dropping into the [Nuxt Discord](https://discord.nuxtjs.org) and the #typescript channel if you have any questions 🙂

At first glance this isn't an issue with the Composition API; it's just a TypeScript question (so I'll be closing the issue).

However, it looks to me like you've defined the type for `$repositories.userRepository.all` as potentially undefined. (See https://github.com/carlomigueldy/nuxt-ts-composition-api-boilerplate/blob/b3e1651279c9ef1054113f52c9e33a7885f2011f/core/interfaces/Repository.ts#L2) So you will need to check that it is in existence before calling it. For example:
```ts
// With optional chaining
context.$repositories.userRepository.all?.()
// without
context.$repositories.userRepository.all && context.$repositories.userRepository.all()
```

**Comment by carlomigueldy** [comment]
Thanks @danielroe !

**Comment by danielroe** [comment]
@carlomigueldy You're very welcome 😊
