### ISSUE TITLE
feat: Enable jsx support

### ISSUE THREAD

**Issue by mathieutu** [nuxt-community/composition-api#303]
Hi, 
When using jsx in setup we have a pretty normal error, which is that `this` is undefined.

An update of the babel plugin seems to fix that: https://github.com/vuejs/jsx/pull/142, and introduce an opt-in option.

It would be cool to set this option to true with this module.

Thanks.

**Comment by mathieutu** [comment]
I can make a PR if you're ok with that, it works well on my project.

**Comment by danielroe** [comment]
@mathieutu I'd love to see a PR - thanks!
