### ISSUE TITLE
feat: make `useMeta` compatible with the root component.

### ISSUE THREAD

**Issue by manniL** [nuxt-community/composition-api#305]
**🆒 Your use case**
Add a description of your use case, and how this feature would help you.
> Ex. When I do [...] I would expect to be able to do [...]

`onGlobalSetup` can be used to set global (layout-independent) values. One thing that'd be great to do there is setting meta data (e.g. the canonical link) which can depend on the current route.
The problem is: `useMeta` has no effect because the root component hasn't been created with `defineComponent`.

**🆕 The solution you'd like**
Somehow create the root Nuxt component with `defineComponent` so vue-meta might have an effect.

**Comment by baixiaoyu2997** [comment]
hi~, i don't understand why use `useMeta` must have `defineComponent`  . i dont use ts

**Comment by mathe42** [comment]
Your defineComponent is not a noop function and doesn't only add better types. The way nuxt works this is the only option to inject some stuff for the header...
