### ISSUE TITLE
help: useAsync useFetch loading

### ISSUE THREAD

**Issue by ralatas** [nuxt-community/composition-api#329]
**📚 What are you trying to do? Please describe.**
I try get Promice in my page using **useAsync** or **useFetch**. When i use **asyncData** in client side - nuxt do default loding (progress line in top part), and after data will be loaded, nuxt do redirect in target page. When i use use **useAsync** or **useFetch**. nuxt make redirect in target page and affer start useAsync hook. How using useAsync give loading how
 use asyncData ? Sorry for my English

**🔍 What have you tried?**
![image](https://user-images.githubusercontent.com/13538789/102646868-d7a7a780-4175-11eb-8c15-b9b6c812058d.png)

**ℹ️ Additional context**
https://nuxtjs.org/docs/2.x/features/loading

**Comment by mathe42** [comment]
When the page is loaded and a navigation happens with the normal `asyncData` nuxt will hold until the data is loaded. With the composition-API this can't be done with the current Nuxt APIs. I wrote `useAsync` with the intention to get as close as we can near the behavior of `asyncData` but when setup is called the navigation already happend.

With Nuxt 3 it is posible to do this but not with Nuxt 2 👎 

Hope that helps

**Comment by ralatas** [comment]
Thanks for the answer

**Comment by Ovyerus** [comment]
> With the composition-API this can't be done with the current Nuxt APIs.

Been having an issue in my SPA with this, been needing to handle the null refs before they resolve, and wondered why this didn't happen before. Is there anyway to possibly use the old `asyncData` alongside the composition API to get the blocking behaviour, or would I need to go back to using the regular options API in order to do so?
