### ISSUE TITLE
fix: Can't open static-json directory error when using useStatic in devloping

### ISSUE THREAD

**Issue by ics-nishihara** [nuxt-community/composition-api#337]
**🐛 The bug**
When I use useStatic, "ENOENT: no such file or directory '.../.nuxt/static-json/foo-bar.json'" error occurs at first access or reload in dev mode.
This error does not cause any other problems, only shows error log.

**🛠️ To reproduce**

1. Use useStatic in code, like [example](https://composition-api.nuxtjs.org/helpers/useStatic).
2. Run "dev" command
3. Access the localhost:3000, browser console shows this error at Nuxt SSR.
4. Reload page, this error is too.

**🌈 Expected behaviour**
This error doesn't shown at in dev mode.

**ℹ️ Additional context**
This error fixed by manually adding the "static-json" folder at .nuxt folder.
The problem caused by not making the folder at dev mode, I think.

Thanks.

**Comment by dpschen** [comment]
Based on the additional context I wrote a hacky workaround that seems to remove the warning for now:

```js
  buildModules: [
    // [...]
    function createStaticJsonDirectory() {
      this.nuxt.hook('builder:prepared', () => {
        const fs = require('fs')
        const path = require('path')

        const dir = path.resolve(
          __dirname,
          this.options.buildDir,
          'static-json/'
        )

        if (!fs.existsSync(dir)) {
          fs.mkdirSync(dir)
        }
      })
    },
  ],
```

**Comment by webcoderkz** [comment]
This error is shown for me even in a dev environment.
