### ISSUE TITLE
help: Property '$axios' does not exist on type 'UseContextReturn'

### ISSUE THREAD

**Issue by carlomigueldy** [nuxt-community/composition-api#341]
**📚 What are you trying to do? Please describe.**
I am trying to add $axios in useContext() type declarations but it doesn't work.

**🔍 What have you tried?**
I have declared it to be in Context interface but it doesn't work and the useContext() still not recognize $axios inside a component.

```
// types/index.d.ts

import { NuxtAxiosInstance } from "@nuxtjs/axios";

declare module "@nuxt/types" {
  interface Context {
    $axios: NuxtAxiosInstance;
  }
}

declare module "@nuxtjs/composition-api" {
  interface Context {
    $axios: NuxtAxiosInstance;
  }
}

declare module "vuex/types/index" {
  interface Store<S> {
    $axios: NuxtAxiosInstance;
  }
}
```

**Comment by danielroe** [comment]
Diagnosed with @carlomigueldy on Discord - this was an ide issue.

**Comment by riderx** [comment]
I got the same issue for 2 other plugin.
Everything you need is documented here :  https://typescript.nuxtjs.org/cookbook/plugins#iii-combined-inject

**Comment by FieldMarshallVague** [comment]
The docs mention TS integration a bit later, so if you're getting this error ( get it, but with $strapi instead of axios), then don't forget to include the types in your tsconfig.


    "types": [
      "@nuxtjs/strapi",
      ...etc.
    ]
