### ISSUE TITLE
feat: Allow `fetch` options when using `useFetch`

### ISSUE THREAD

**Issue by rijkvanzanten** [nuxt-community/composition-api#342]
**🆒 Your use case** / **🆕 The solution you'd like**

I'd like to rely on the existing options for `fetch` (https://nuxtjs.org/docs/2.x/components-glossary/pages-fetch#options) when using `useFetch`. This allows me—among other things—to configure it to not fetch on the server by setting `fetchOnServer` to false.
Describe what you want to happen.

**Comment by pleinon** [comment]
Sorry for necro but how does one set fetchOnServer-flag on `script setup`?

**Comment by danielroe** [comment]
@pleinon You would have to add an additional script block for that option.

```vue
<script setup>
//...
</script>

<script>
export default {
  fetchOnServer: false
}
</script>
```
