### ISSUE TITLE
help: reqSsrRef deprecation? What should I use instead?

### ISSUE THREAD

**Issue by MikeSaprykin** [nuxt-community/composition-api#350]
**📚 What are you trying to do? Please describe.**
A clear and concise description of your objective. Ex. I'm not sure how to [...].

I'm planning to replace vuex state management with custom state management based on composition API.
For my purpose, looks like reqSsrRef is a perfect fit, for avoiding duplication of ssr state for different clients and using state outside of components, but currently in docs reqSsrRef and reqRef is deprecated. So what should I replace it with, since this is deprecated?

**🔍 What have you tried?**
Have you looked through the docs? Tried different approaches? The more detail the better.
I've created state management with reqSsrRef and it looks like working fine.

**ℹ️ Additional context**
Add any other context or information.

**Comment by lennartzellmer** [comment]
I am in the same situation that I use `reqRef` and `ssrReqRef` in a project and do not know what my alternatives are. The documentation seems to be quite limited in this area. Especially regarding shared ssr state.

**Comment by MikeSaprykin** [comment]
@lennartzellmer what I end up with as a temporary solution - I'm still placing the state into Vuex, but describing it as just state and mutations. Also I found another bug related to reqSsrRef ( which is no need to report since this is deprecated ) so decided to stick with this vuex/composition pattern for now

I'm using composition functions, which are just exposing computed properties of pieces of state (aka getters in vuex) and all actions are just composition functions which are, for example, calling async service and calling commit with mutation to state

Something like that

```ts
import { computed, useContext } from '@nuxtjs/composition-api';
import { UseContextReturn } from '@/shared';
import { PostsMutations } from './posts.state';
import { usePostsService } from './use-posts-service';

export function usePosts(context?: UseContextReturn) {
  // If we want to use this composition function in middleware, we have to pass context from middleware, as useContext can only
  // be used in component setup function
    if (!context) {
        context = useContext();
    }

    const {
        store: { commit, state },
        $axios,
    } = context;

    const postsService = usePostsService($axios);

    const posts = computed(() => state.posts.items);
    const selectedPost = computed(() => state.posts.selectedPost);

    async function selectPost(id: number) {
        const post = await postsService.loadPost(id);
        commit(PostsMutations.SET_SELECTED_POSTS, post);
    }

    async function loadPosts() {
        const posts = await postsService.loadPosts();
        commit(PostsMutations.SET_PELOTON_POSTS, posts);
    }

    return {
        posts,
        selectedPost,
        selectPost,
        loadPosts,
    };
}


```

and state file

```ts
import { MutationTree, Module } from 'vuex';
import { Nullable } from '@/shared';
import { Post } from '../types';

export interface PostsState {
    items: Post[];
    selectedPost: Nullable<Post>;
}

export enum PostsMutations {
    SET_SElECTED_POST = 'SET_SElECTED_POST',
    SET_POSTS = 'SET_POSTS',
}

const mutations: MutationTree<PostsState> = {
    [PostsMutations.SET_SElECTED_POST]: (state, payload: Nullable<Post>) => {
        state.selectedPost = payload;
    },
    [PostsMutations.SET_POSTS]: (state, payload: Post[]) => {
        state.items = payload;
    },
};

export const postsState: Module<PostsState, any> = {
    mutations,
    state: (): PostsState => ({
        items: [],
        selectedPost: null,
    }),
};
```
