### ISSUE TITLE
fix: Computed Property not updating when imported from composable function

### ISSUE THREAD

**Issue by DotCoyote** [nuxt-community/composition-api#354]
**🐛 The bug**
Hi everyone!
I got problems with a computed property inside a composable function. Basically, I have a computed prop in a [composable function](https://codesandbox.io/s/autumn-night-1vsyp?file=/composition/sort.js) which is generated by a prop [passed to the composable](https://codesandbox.io/s/autumn-night-1vsyp?file=/components/UserList.vue).

The computed prop itself reacts to the props-changes (when logging in the computed prop, it logs every time the prop changes), but does not update the exported variable.

**🛠️ To reproduce**
https://codesandbox.io/s/autumn-night-1vsyp

1. Click on the Button "Admin"
2. See that only props.users and the computed prop directly from the component is showing

On local development, when HMR is triggered or I manually refresh the page on the admin-page, the `sortedUsers`-list is showing. 

**🌈 Expected behaviour**
The reactive computed prop works when returned from a composable function.

**Comment by danielroe** [comment]
This is because you access `props.users` directly in your setup function in `UserList`, but that is not reactive. In order to get a ref that is kept up to date you could do something like the below, and amend your composable to accept a ref.
```ts
const { users } = toRefs(props)
```
