### ISSUE TITLE
feat: export `UseContextReturn`

### ISSUE THREAD

**Issue by dzcpy** [nuxt-community/composition-api#360]
**🆒 Your use case**
Add a description of your use case, and how this feature would help you.
> I was trying to get the cookie-universal-nuxt module work in my project. I need to get $cookies from the context returned by useContext. However it $cookies doesn't exist in UseContextReturn and there's no way for me to extend it since it's not exported.

**🆕 The solution you'd like**
Can you please export this type?

**🔍 Alternatives you've considered**
By the way, I ended up using this workaround, which seems to be a bit ugly:
```ts
const {
  $axios,
  $cookies,
}: {
  $axios: NuxtAxiosInstance
  $cookies: NuxtCookies
} = useContext() as any
```

**ℹ️ Additional info**
No

**Comment by mathe42** [comment]
Do you have https://axios.nuxtjs.org/setup#typescript in your tsconfig?

**Comment by mathe42** [comment]
Did you add cookie-universal-nuxt in the types Array in your tsconfig?

**Comment by reslear** [comment]
@dzcpy  use
```ts
 ctx: ReturnType<typeof useContext>,
```

**Comment by dzcpy** [comment]
@mathe42 Just tried that, and it works perfectly. Thanks!

**Comment by dzcpy** [comment]
@mathe42 Just tried that, and it didn't work
![image](https://user-images.githubusercontent.com/203980/106972501-eed53f80-678b-11eb-9c80-e018c2f43b18.png)

**Comment by mathe42** [comment]
1. Post your tsconfig.json
2. Did you restart your editor?

**Comment by dzcpy** [comment]
> @dzcpy Looking at the [type declaration](https://github.com/microcipcip/cookie-universal/blob/162cf86e2a4aca6c339b081f150341c0887997d9/packages/cookie-universal-nuxt/types/index.d.ts#L32), you will need to access it from app - so:
> 
> ```ts
> const { app: { $cookies } } = useContext()
> ```
> 
> In other cases though, you shouldn't augment UseContextReturn - just augment Nuxt types in the normal way and it will pick it up - [see docs](https://typescript.nuxtjs.org/cookbook/plugins/#plugin-2).

Thanks, it worked for me.
