### ISSUE TITLE
help: How to use 'this.$nuxt.refresh()'

### ISSUE THREAD

**Issue by cluyun** [nuxt-community/composition-api#370]
**📚 What are you trying to do? Please describe.**
A clear and concise description of your objective. Ex. I'm not sure how to [...].
composition-api how use ```this.$nuxt.refresh()```
https://nuxtjs.org/docs/2.x/internals-glossary/$nuxt#refreshing-page-data

**🔍 What have you tried?**
Have you looked through the docs? Tried different approaches? The more detail the better.
The related document was not found

**ℹ️ Additional context**
Add any other context or information.
Is there a missing description ？

**Comment by mathe42** [comment]
You can get $nuxt with:

```ts
defineComponent({
   setup(props, ctx) {
     ctx.root.$nuxt
   }
})

```

**Comment by cluyun** [comment]
> You can get $nuxt with:
> 
> ```ts
> defineComponent({
>    setup(props, ctx) {
>      ctx.root.$nuxt
>    }
> })
> ```

Thank you for your reply. But it didn't work.
code:
```TypeScript
import { defineComponent, ref, useAsync, useContext } from "@nuxtjs/composition-api";

export default defineComponent({
  setup: function (props: any, context: any) {

    function refresh() {
      context.root.$nuxt.refresh();
      console.log(context.root);
      console.log(context.$nuxt);
      console.log(context.refresh);
    }


    return { refresh };
  },
});
```
output:
```txt
xxx?920d:8 Vue {_uid: 0, _isVue: true, $options: {…}, _renderProxy: Proxy, _self: Vue, …}
xxx.ts?920d:9 undefined
xxx.ts?920d:10 undefined
```

**Comment by mathe42** [comment]
First log looks good. In the others you should log `context.root.$nuxt` and `context.root.$nuxt.refresh` this should result in not undefined values

**Comment by mathe42** [comment]
Note that $nuxt.refetch might have different behavior if you use `useFetch` and `useAsync`. I think nothing happens when you call $nuxt.refetch()

**Comment by cluyun** [comment]
> Note that $nuxt.refetch might have different behavior if you use `useFetch` and `useAsync`. I think nothing happens when you call $nuxt.refetch().

thank you。It's solved。

**Comment by cluyun** [comment]
> First log looks good. In the others you should log `context.root.$nuxt` and `context.root.$nuxt.refresh` this should result in not undefined values

No problem code：
```TypeScript
import { defineComponent } from "@nuxtjs/composition-api";

function getMsg() {
  if (Math.random() >= 0.5) {
    return "1111";
  }
  return "222";
}

export default defineComponent({
  asyncData: function () {
    return { msg: getMsg() };
  },
  setup: function (props: any, context: any) {

    function refresh() {
      context.root.$nuxt.refresh();
      console.log(context.root);
      console.log(context.root.$nuxt);
      console.log(context.root.$nuxt.refresh);
    }


    return { refresh };
  },
});
```
