### ISSUE TITLE
help:  defineNuxtConfig not found

### ISSUE THREAD

**Issue by blazejwcislo** [nuxt-community/composition-api#371]
I'm not sure if the docs are wrong or if it's me.
I wanted to create nuxt.config.ts file like was mentioned in https://composition-api.nuxtjs.org/typings/definitionHelpers - unfortunately I'm getting this error` 'Module '"./node_modules/@nuxtjs/composition-api/lib"' has no exported member 'defineNuxtConfig''`

I've tried looking into .nuxt\composition-api\index.js and I can't find export of 'defineNuxtConfig ' - is that something that was removed recently and docs are inconsistent with changes? Or it's quite the opposite and this feature will be added in the future?

Thanks!

**Comment by danielroe** [comment]
@blazejwcislo It's the opposite - it's a new feature that will be present in the next release of the module. Sorry for the inconvenience!

**Comment by blazejwcislo** [comment]
Thanks!
