### ISSUE TITLE
fix: fetch typo

### ISSUE THREAD

**Issue by reslear** [nuxt-community/composition-api#372]
hi @danielroe please see
```
"@nuxtjs/auth-next": "5.0.0-1612791489.a5d8c28",
"@nuxtjs/composition-api": "^0.20.0",
```
fetch return void (error for destructuring  - `fetchState` `fetch` etc..)

<img width="765" alt="Снимок экрана 2021-02-15 в 11 15 21" src="https://user-images.githubusercontent.com/12596485/107921711-f52f9c80-6f7f-11eb-8d9c-0c9cd3b0368e.png">

 
```ts
const { fetch, fetchState } = useFetch(async () => {
```

v0.20
<img width="544" alt="Снимок экрана 2021-02-15 в 11 20 34" src="https://user-images.githubusercontent.com/12596485/107921612-d3361a00-6f7f-11eb-8dd1-5e4dd54aafa9.png">

v0.19
<img width="544" alt="Снимок экрана 2021-02-15 в 11 36 58" src="https://user-images.githubusercontent.com/12596485/107923137-1db89600-6f82-11eb-8a49-332a54cbebf2.png">

maybe this problem line
https://github.com/nuxt-community/composition-api/blob/796935704492b641f952681fa6bd8e8fe1575571/src/fetch.ts#L304

**Comment by danielroe** [comment]
@reslear Really appreciate this - should now be fixed in `@nuxtjs/composition-api@0.20.1`. ❤️
