### ISSUE TITLE
fix: Always running into the not registered warning

### ISSUE THREAD

**Issue by sebastianhoitz** [nuxt-community/composition-api#376]
**🐛 The bug**
I am building a nuxtjs application that also provides an API to fetch data. I have a small middleware that provides access to methods that query my database. When rendering the page on the server, I however directly call these methods and don't fetch the information from the API.

I have a small function that basically decides if I am doing a serverside rendering or not and then calls those database functions. I was using 0.18.1 before and conditionally called the `useContext` method to provide session information to these methods.

However, now with the latest changes I always run into the fatal error, that nuxt/composition-api is not registered in my middleware, which is correct, but I am not calling it anyway, I have to import some of the methods so for the case that the function is called directly from within nuxt.

So, to better explain:

```
Scenario 1: Called through SSR

Call Method -> get context from nuxt -> call data access function

Scenario 2: Called through API

Call API -> have context in req object, no need to call nuxt (FATAL ERROR) <--- here it breaks, because I am importing useContext in my file, but I am not calling it
```

**🌈 Expected behaviour**
I should be able to silence these errors or have any other means to not execute this check.

**ℹ️ Additional context**

**Comment by sebastianhoitz** [comment]
Hm... I don't think that is ideal...

Ok I further pin-pointed the issue. We are using a monorepo and have a package that provides core functionality. This is the package that also exports the API middleware but also some composables.

Basically everywhere where we are now using this package we will get the fatal error, since the package also exports the composables, which import nuxtjs/composition-api.

I was able to workaround this by only importing the specific path from within our core module, but I don't think this scenario is ideal. So we are now exchanging first time user DX with real world DX?

As I said, maybe you could provide a way to prevent or disable this check?

**Comment by danielroe** [comment]
I'm closing this as I've not heard back, but please do feel free to let me know more at any point and I'll reopen this.
