### ISSUE TITLE
docs: Highlight new composables

### ISSUE THREAD

**Issue by manniL** [nuxt-community/composition-api#378]
I haven't noticed new documentation entries for composables until now because they aren't "marked" (as e.g. in the [nuxt content docs](https://content.nuxtjs.org/themes/docs)).
![grafik](https://user-images.githubusercontent.com/640208/108255103-1947d500-715c-11eb-8185-5f46cf91f7a1.png)

It'd be super helpful if people can immediately see that new content exists by having the sections highlighted with a small pulsin dot.

**Suggested**

![grafik](https://user-images.githubusercontent.com/640208/108255005-f1f10800-715b-11eb-812e-4e77b65adb1f.png)

**Current**
![grafik](https://user-images.githubusercontent.com/640208/108255030-f9b0ac80-715b-11eb-854a-4eda5b3480b5.png)

**Comment by danielroe** [comment]
Good catch!

**Comment by manniL** [comment]
Looks like the badge is still missing 🙈)

**Comment by manniL** [comment]
Could be indeed. 🤔
