### ISSUE TITLE
fix: WARN Cannot stringify a function

### ISSUE THREAD

**Issue by dnldsht** [nuxt-community/composition-api#386]
**🐛 The bug**
When I return a function inside the `setup` function I get these warnings:
- Server: WARN Cannot stringify a function
- Client: [Vue warn]: Avoid adding reactive properties to a Vue instance or its root $data at runtime - declare it upfront in the data option.

**🛠️ To reproduce**
```vue
<script lang="ts">
import { defineComponent } from "@nuxtjs/composition-api";

export default defineComponent({
  setup() {
    const test = () => {}
    return { test };
  },
});
</script>
```

**🌈 Expected behaviour**
Since this is the official approach to make event handlers available to the template and it's the way it's taught in the docs, this should just work without warnings.

**ℹ️ Additional context**
ssr must be enabled

**Comment by danielroe** [comment]
@dnldsht Would you provide a reproduction?

**Comment by dnldsht** [comment]
I've found out that this issue appears only when you use both `fetch` and `setup`

```vue
<script lang="ts">
import { defineComponent } from "@nuxtjs/composition-api";

export default defineComponent({
  fetch() {},
  setup() {
    const test = () => {}
    return { test };
  },
});
</script>
```
here is sandbox https://codesandbox.io/s/angry-sun-u8mq7?file=/pages/index.vue

**Comment by danielroe** [comment]
Indeed. Unfortunately it's an unavoidable consequence of how `fetch` works - it stringifies all data properties on the instance and tries to rehydrate them on the client-side. See also https://github.com/nuxt-community/composition-api/issues/19.
