### ISSUE TITLE
Error when running test with jest

### ISSUE THREAD

**Issue by lletestu** [nuxt-community/composition-api#405]
Hello, I try to run a test with Jest in my project.

**:bug: Bug :**
I created a jest unit test. I imported a Vue component is built with `@nuxtjs/composition-api`. However, I have an error `SyntaxError: Cannot use import statement outside a module`. 

**:wrench: To reproduce / context  :**

1. Npm module for test : 
```
  "@types/jest": "^26.0.20",
  "@vue/test-utils": "^1.1.3",
  "jest": "^26.6.3",
  "ts-jest": "^26.5.3",
  "vue-jest": "^3.0.7"
```
  
2. Create jest.config.js
```
const { defaults: tsjPreset } = require('ts-jest/presets')

module.exports = {
  preset: 'ts-jest',
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1',
    '^~/(.*)$': '<rootDir>/$1',
    '@nuxtjs/composition-api': '@nuxtjs/composition-api/lib/entrypoint.js'
  },
  moduleFileExtensions: ['ts', 'js', 'vue', 'json'],
  transform: {
    ...tsjPreset.transform,
    '^.+\\.vue$': 'vue-jest'
  }
}
```

tsonfig.js file
```
{
  "compilerOptions": {
    "target": "ES2018",
    "module": "ESNext",
    "moduleResolution": "Node",
    "lib": [
      "ESNext",
      "ESNext.AsyncIterable",
      "DOM"
    ],
    "esModuleInterop": true,
    "allowJs": true,
    "sourceMap": true,
    "strict": true,
    "noEmit": true,
    "experimentalDecorators": true,
    "baseUrl": ".",
    "paths": {
      "~/*": [
        "./*"
      ],
      "@/*": [
        "./*"
      ]
    },
    "types": [
      "node",
      "@nuxt/types",
      "@nuxtjs/strapi",
      "jest"
    ]
  },
  "include": ["types", "**/*.ts", "**/*.vue"],
  "exclude": [
    "node_modules",
    ".nuxt",
    "dist"
  ]
}

```

3. Create a simple test : 
```
import { mount } from '@vue/test-utils'
import News from '@/pages/news.vue'

describe('News', () => {
  it('is a Vue component', () => {
    const wrapper = mount(News)
    expect(wrapper).toBeTruthy()
  })
})
```

4. A simple page under ./pages/news.vue : 
```
<template>  [ ... ] </template>

<script lang="ts" >
import { CampaignCollection } from '@/types/campaign'
import { computed, onMounted, ref, useStore, defineComponent } from '@nuxtjs/composition-api'

export default defineComponent({
  name: 'News',
  setup () {
    const store = useStore()
   [ ... ]
    return { isLoading, campaigns, selectedCampaign }
  }

})
</script>
```

**:-1:  Debug console  :**
```
/app/pages/news.vue:2
    import { computed, onMounted, ref, useStore, defineComponent } from '@nuxtjs/composition-api';
    ^^^^^^
    SyntaxError: Cannot use import statement outside a module
```

**:computer: Stack :**
It's a nuxt project with typescript.
- nuxt version : 2.16.6
- jest verstion : 26.6.3
- nuxt/composition-api version : 0.20.2

Thanks in advance for your help :pray: !

**Comment by lletestu** [comment]
@danielroe : Yes it works, I tried the simple component 'Logo.vue'. But when I try to import Composition API it's fail. Perhaps the declaration is wrong in jest config.. But normally with declaration in moduleNameMapper it should work.

**Comment by danielroe** [comment]
@lletestu Could you provide a reproduction? 🙏

**Comment by lletestu** [comment]
@danielroe I added tsconfig.json file in my first message. I put all files. What do you need more ?

**Comment by lletestu** [comment]
@danielroe Indeed I noticed that this issue happens only when I'm running `npm run test` inside my docker container. Thank you for your time I will dig into this docker issue.

**Comment by lletestu** [comment]
@danielroe I find the solution, we just need to set in packages.json : `"test": "NODE_ENV=test jest"` to run test.

**Comment by danielroe** [comment]
@lletestu Glad you found the issue 😊
