### ISSUE TITLE
fix: Ref Arrays do not work

### ISSUE THREAD

**Issue by caboe** [nuxt-community/composition-api#411]
**🐛 The bug**
When referencing elements dynamically in a v-for loop, references (ref) are not created.

**🛠️ To reproduce**
1. Clone https://github.com/caboe/test-refs
2. Start app
3. Look in the browser console
4. console.log prints out an empty array

**🌈 Expected behaviour**
console.log should print out an array of three divs, as it is in Vue3 (https://github.com/caboe/ref-test)

**Comment by danielroe** [comment]
@caboe The Vue 2 Composition API does not support function refs - see [limitations](https://github.com/vuejs/composition-api#template-refs).
