### ISSUE TITLE
fix: bug @vue/apollo-composable

### ISSUE THREAD

**Issue by Rasool-deldar** [nuxt-community/composition-api#413]
**🐛 The bug**

import { Context } from '@nuxt/types';
import { provide, onGlobalSetup, defineNuxtPlugin } from "@nuxtjs/composition-api";
import { DefaultApolloClient } from "@vue/apollo-composable";

/**
 * This plugin will connect @nuxt/apollojs with @vue/apollo-composable
 */

export default defineNuxtPlugin(({ app }: Context): void => {
  onGlobalSetup(() => {
    provide(DefaultApolloClient, app.apolloProvider?.defaultClient);
  });
})

My project has an error, please tell me how to solve this problem

Cannot read property 'DefaultApolloClient' of undefined

I have the same problem with my project
nuxt - 2.15.3
@nuxtjs/apollo - 4.0.1-rc.5
@nuxtjs/composition-api - 0.22.1
@vue/apollo-composable - 4.0.0-alpha.12

Console error
ERROR [Vue warn]: Error in data(): "TypeError: Cannot read property 'DefaultApolloClient' of undefined"

I tested on a project, it worked on version 11, on versions 0.20.0, 0.21.0, 0.22.0 and 0.22.3, this gives an error, please follow .

link test ( display error ) - https://codesandbox.io/s/elastic-satoshi-otjer?file=/nuxt.config.js

for example
link - I tested on a project . https://github.com/shenron/vue-nuxt-tsx

project - Show error using @nuxtjs/composition-api versions 0.20.0, 0.21.0, 0.22.0 and 0.22.3
[vue-nuxt-tsx.zip](https://github.com/nuxt-community/composition-api/files/6182582/vue-nuxt-tsx.zip)

**Comment by danielroe** [comment]
@Rasool-deldar This is an issue in `@vue/apollo-composable` - it's not updated to work with the latest `@vue/composition-api`. [Here's a reproduction](https://codesandbox.io/s/sleepy-buck-t3g24?file=/package.json) that doesn't use the Nuxt Composition API. I suggest you raise an issue [there](https://github.com/vuejs/vue-apollo/issues/).
