### ISSUE TITLE
fix: Error: use getRouteBaseName function from setup root context inside computed on server side

### ISSUE THREAD

**Issue by LouisMazel** [nuxt-community/composition-api#425]
**🐛 The bug**
What isn't working? Describe what the bug is.

On reload (server side): When you use the `getRouteBaseName` function from the setup root context inside a computed, an error is render : `Cannot read property 'req' of undefined`

By the way: `$route` from setup root context is not reactive. On update, watch and computed are not triggered
 
**🛠️ To reproduce**

```html
<template>
  <div>
    {{ routeBaseName }}
  </div>
</template>
```

```ts
<script lang="ts">
import { defineComponent, computed, useRoute } from '@nuxtjs/composition-api'

export default defineComponent({
    name: 'MyAccount',
    setup(_, { root: { getRouteBaseName } }) {
      const route = useRoute()

      const routeBaseName = computed(() => {
        return getRouteBaseName(route.value)
      })

      return {
        routeBaseName,
      }
    }
  })
</script>
```

**🌈 Expected behaviour**
No error with request parameters, there is no need  :) 

**Informations**

- nuxt: 2.15.3
- @nuxtjs/composition-api: ^0.22.1
- Typescript

**Comment by LouisMazel** [comment]
@danielroe

**[Reproduction link with my own code](https://codesandbox.io/s/get-route-base-name-error-bd8iw)**

**[Reproduction link with your code proposal](https://codesandbox.io/s/get-route-base-name-error-forked-1kbgd)**

Same error on both.

 Thanks your answer and your time :)

**Comment by LouisMazel** [comment]
Oh my bad, I will check again the link with your proposal and it's works now (codesandbox cache issue when I tested it the first time I thinks)

So, we only have an issue when we use the `getRouteBaseName` function from setup context

**Comment by rchl** [comment]
I'd suggest:

```ts
import { useContext } from "@nuxtjs/composition-api";

export default defineComponent({
  setup(_) {
    const { getRouteBaseName } = useContext();
// ...
```

Also, you need to add `nuxt-i18n` to `types` array in `tsconfig.json`.
