### ISSUE TITLE
help: How to add a function as custom plugin(typescript)?

### ISSUE THREAD

**Issue by torugok** [nuxt-community/composition-api#439]
**📚 What are you trying to do? Please describe.**
 I'm not sure how to add function as custom plugin. I've been trying to put the pusher on my project, in this case it's a normal javascript library.

**🔍 What have you tried?**
My file on plugins:
![Screenshot from 2021-04-02 21-36-36](https://user-images.githubusercontent.com/1656859/113463318-85745480-93fb-11eb-846e-ce89de8f842b.png)

![Screenshot from 2021-04-02 21-35-34](https://user-images.githubusercontent.com/1656859/113463291-65449580-93fb-11eb-92bb-69422fe8c5e0.png)

![Screenshot from 2021-04-02 21-26-55](https://user-images.githubusercontent.com/1656859/113463043-2c57f100-93fa-11eb-8390-29a74776726e.png)

![Screenshot from 2021-04-02 21-28-11](https://user-images.githubusercontent.com/1656859/113463100-6c1ed880-93fa-11eb-9eb7-0595e12857f5.png)

![Screenshot from 2021-04-02 21-28-33](https://user-images.githubusercontent.com/1656859/113463103-6f19c900-93fa-11eb-90d9-5249624a84f8.png)

My result calling the $pusher from useContext():
![Screenshot from 2021-04-02 21-30-25](https://user-images.githubusercontent.com/1656859/113463148-a9836600-93fa-11eb-89bc-7ed13ada6d4e.png)

**ℹ️ Additional context**
I'm based in the article: https://dev.to/carlomigueldy/getting-started-with-nuxt-composition-api-typescript-417f, trying follow the steps, but not succesfull

Pusher-js: https://www.npmjs.com/package/pusher-js

Apologies for the trivial question :+1:

**Comment by torugok** [comment]
I achieved the result expected, changing the form of "pusher-js.ts" to:
![Screenshot from 2021-04-03 01-11-33](https://user-images.githubusercontent.com/1656859/113467476-916f0f00-9419-11eb-8ec8-17707c9c33b5.png)

Sorry for inconvenience

**Comment by danielroe** [comment]
@torugok Great! 😊
