### ISSUE TITLE
fix: useStatic not generating static JSON files

### ISSUE THREAD

**Issue by madc** [nuxt-community/composition-api#449]
**🐛 The bug**
When using `useStatic` in a component, the requests to the static JSON-files result in a 404-response. This happens both in dev and prod environment (via nuxt generate).
When looking into the `dist/`folder, the JSON files have not been generated. On `nuxt build`, the `.nuxt/static-json/` folder is created, but remains empty.
We are currently working on two statically generated websites and see the same behavior.

**🛠️ To reproduce**

This is a very bare-bone example:

```
<script>
import {
  defineComponent,
  watch,
  ref,
  useStatic,
} from '@nuxtjs/composition-api'
import axios from 'axios'

export default defineComponent({
  setup() {
    const id = ref(1)
    const user = useStatic(
      (id) => axios.get(`https://jsonplaceholder.typicode.com/users/${id}`),
      id,
      'users'
    )

    watch(user, () => {
      if (user.value === null) {
        return
      }

       console.log('###users', user)
    })

    return {}
  },
})
</script>
```
Running `nuxt generate` and  `nuxt start` results in these network requests:

![image](https://user-images.githubusercontent.com/343392/114264862-b5b88600-99ed-11eb-8fec-3dec80b77940.png)

![image](https://user-images.githubusercontent.com/343392/114264847-a3d6e300-99ed-11eb-881b-3f72f3cfaf7e.png)

![image](https://user-images.githubusercontent.com/343392/114264891-e698bb00-99ed-11eb-923c-19831ac22bd6.png)

![image](https://user-images.githubusercontent.com/343392/114264903-f6b09a80-99ed-11eb-8821-5814c826b094.png)

Please let me know, if I can provide any additional information.

**🌈 Expected behaviour**
The JSON-file is written on ǹuxt generate` and the statically generated website does not hit the actual API-Endpoint anymore.

**ℹ️ Additional context**
We are on `nuxt` v2.15.4 and `nuxt/composition-api` v0.22.4.

**Comment by madc** [comment]
Turns out, sometimes it is enough to write a bug report to find a solution.
Setting `ssr: true` in my `muxt.config.js` resolved the issue.

**Comment by danielroe** [comment]
Great - glad all is well 😊
