### ISSUE TITLE
help: Different `onMounted` hook behaviour opening page with nuxt-link than after page refresh

### ISSUE THREAD

**Issue by szopqa** [nuxt-community/composition-api#453]
**📚 What are you trying to do? Please describe.**
Hello, 
I'have a following code in my setup function in one of my page components: 

` setup: (_, ctx) => {
    const topNavigationHeight = ref<Number>(0);

    onMounted(() => {
      const topNavigation = ctx?.parent?.$parent.$el as HTMLElement;
      topNavigationHeight.value = topNavigation.offsetTop;
    });

    return {
      topNavigationHeight,
    };
  },
`
What I'am trying to do here is to retrieve height of parent component (in this case it's default page layout) and pass it further as a reference. Everything seem to work fine after direct page refresh (pressing F5 on page results in correct value being saved), but accessing same page using nuxt-link (navigation from one page to another) results in not saving correct value (value of 0 is never replaced).

I initially though that in this case for some reason nuxt can't access parent component, but console log shows that it's there.
It looks like after nuxt-link navigation page 'onMounted' hook is launched before nuxt loaded all context (including parent components).

**🔍 What have you tried?**
I've wrapped all that part with setTimeout 
`
  setup: (_, ctx) => {
    const topNavigationHeight = ref<Number>(0);

    onMounted(() => {
      setTimeout(() => {
        const topNavigation = ctx?.parent?.$parent.$el as HTMLElement;
        topNavigationHeight.value = topNavigation.offsetTop;
      }, 100);
    });

    return {
      topNavigationHeight,
    };
  },
`
and after that it worked fine in both cases (for nuxt link and refresh). I've even tried using value of '0' for timeout and in this case it also worked fine.

I've also replaced use of ctx.parent with ctx.ref (ref was added to page component), but it worked exactly the same way.

Could you please tell me if I'am doing something wrong? In my understanding page component should behave in the same way no matter how they are fired, am I right? 

Regards

**Comment by szopqa** [comment]
@danielroe I've tried approach with `nextTick`, but it didn't work at all (compared to timeout with 0, which works).
`    
onMounted(() => {
      nextTick(() => {
        const topNavigation = ctx?.parent?.$parent.$el as HTMLElement;
        topNavigationHeight.value = topNavigation.offsetTop;
      });
      console.log(topNavigationHeight.value); // 0 displayed
});
`

**Comment by danielroe** [comment]
@szopqa I'll happily take a look if you prepare a reproduction on CodeSandbox.

**Comment by szopqa** [comment]
@danielroe I tried, but as I expected everyhing works fine on simple example, but here's the link: https://codesandbox.io/s/nuxt-composition-api-demo-forked-xf8gk?file=/layouts/default.vue. In my solution there is also some async data fetch, but currently I can't provide better example.

I've also found that composition API allows for template refs (https://v3.vuejs.org/guide/composition-api-template-refs.html#template-refs), but it doesn't seem to be working with nuxt composition api, does it? I've checked in both my project and mentioned code sandbox.

**Comment by szopqa** [comment]
@danielroe I think I've found an issue on my end. 
Here's the code that didn't work
```
<template>
  <main v-if="someExampleApiData">
      <ComponentA
        :someExampleApiData="someExampleApiData"
        :top-navigation-bar-height="topNavigationHeight"
      />
  </main>
</template>

 setup: (_, ctx) => {
    const topNavigationHeight = ref<Number>(0);

    onMounted(() => {
      const topNavigation = ctx?.parent?.$parent.$el as HTMLElement;
      topNavigationHeight.value = topNavigation.offsetTop;
    });

    const { someExampleApiData } = useGetDataById(ctx.root.$route.params.id, ctx);

    return {
      someExampleApiData,
      topNavigationHeight,
    };
  },
```

For some reason replacing `v-if` at <main> element with separate <div> wrapping all my inner components seem to solve my problem (see fixed template below).

```
<template>
  <main>
      <div v-if="someExampleApiData" >
          <ComponentA
            :someExampleApiData="someExampleApiData"
            :top-navigation-bar-height="topNavigationHeight"
          />
    </div>
  </main>
</template>
```

I've tried to prepare some example sandbox which will be similar to my current codebase. Please check this link: https://codesandbox.io/s/nuxt-composition-api-demo-forked-xf8gk?file=/pages/details/_id.vue. In `_id.vue` file I've prepared html for two 'main' tags, which differ only in 'v-if' placement. For first option offset value is 70 whereas second (currently commented) saves value of 8. Do you have any idea why does it happen?

**Comment by szopqa** [comment]
@danielroe, I think we can close this one. It seems like problems were on my end. Thanks for yout time :)
