### ISSUE TITLE
fix: [NuxtCompositionApi@0.23.1] Cannot use composition-api inside middleware

### ISSUE THREAD

**Issue by LouisMazel** [nuxt-community/composition-api#457]
**🐛 The bug**

Since 0.23.x: Inside the `middleware` folder, my middleware use the composition-api and this error is thrown :

`[vue-composition-api] must call Vue.use(VueCompositionAPI) before using any function.`

**🛠️ To reproduce**

[Reproduction Link with codesandbox](https://codesandbox.io/s/nuxt-composition-api-ts-template-9ivpx)

**ℹ️ Additional context**

If you want any other informations, ask me;

**Comment by danielroe** [comment]
This should be fixed in `v0.23.2` - let me know if that doesn't fix it for you.
