### ISSUE TITLE
fix: FATAL  Module should export a function: @nuxtjs/composition-api

### ISSUE THREAD

**Issue by GaborTorma** [nuxt-community/composition-api#469]
**🐛 The bug**
After upgrade to 0.23.0 get a following error message immedietely to npm run dev:
 FATAL  Module should export a function: @nuxtjs/composition-api      16:51:00

  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:217:13)
  at node_modules/@nuxt/utils/dist/utils.js:639:43
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:51:7)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:478:5)

  ✖ Nuxt Fatal Error                            

   TypeError: Module should export a function:   
   @nuxtjs/composition-api                       
  

**🛠️ To reproduce**

refresh to 0.23.0 or newer

**Comment by danielroe** [comment]
@GaborTorma `0.23.0`+ has a new format for registering the module - see https://github.com/nuxt-community/composition-api/releases/tag/0.23.0 for all the details.

**Comment by GaborTorma** [comment]
Solution:

Looks like the location for module import changed, and the Quick Start guide has now been updated to reflect the changes. You now need to use '@nuxtjs/composition-api/module' in buildModules instead of '@nuxtjs/composition-api
