### ISSUE TITLE
fix: ssrRef not usable within onGlobalSetup process.server

### ISSUE THREAD

**Issue by daikiojm** [nuxt-community/composition-api#498]
**🐛 The bug**

ssrRef not usable within onGlobalSetup process.server

**🛠️ To reproduce**

codesandbox:
https://codesandbox.io/s/beautiful-blackwell-x4zfl?file=/plugins/auth.ts

sample repo:
https://github.com/daikiojm/nuxt-composition-api-ssr-ref

**🌈 Expected behaviour**
ssfRef can be defined within onGlobalSetup.

**ℹ️ Additional context**
It would be helpful if you could point out if my usage of `process.server` was wrong.

ref: https://github.com/nuxt-community/composition-api/issues/379#issuecomment-860188871

**Comment by holylovelqq** [comment]
same error to me `Cannot read property 'context' of undefined`
I think [here](https://github.com/nuxt-community/composition-api/blob/842a724ccaa26e6e7812f6d6ac7cce4ef49de506/src/runtime/composables/ssr-ref.ts#L46) should be same with line 35 (`vm[globalNuxt]` -> `(vm[globalNuxt] || vm.$options)` )
