### ISSUE TITLE
feat: support new Grammar sugar like '<script setup></script>' ?

### ISSUE THREAD

**Issue by little3201** [nuxt-community/composition-api#505]
**🆒 Your use case**
vue3 has a new Grammar sugar like : 
```js
<script setup></script>
```
does support it ?

> Ex. When I do [...] I would expect to be able to do [...]

**🆕 The solution you'd like**
support new Grammar sugar like '<script setup></script>'.

**🔍 Alternatives you've considered**
No

**ℹ️ Additional info**
No

**Comment by danielroe** [comment]
This is sadly not yet supported in vue2.

**Comment by AndrewBastin** [comment]
This might be relevant to you: https://github.com/antfu/vue2-script-setup-transform
