### ISSUE TITLE
help: Create Error page on server side

### ISSUE THREAD

**Issue by jonrezun** [nuxt-community/composition-api#512]
Hi, i have some question. I try to create Error page on server side while getting data by useAsync. I use useContext and Error function but it doesn't stop "setup" and works not like redirect. At first I see my page and after a second my Error page (from layout). How can i achieve the same behavior like in asyncData or just deal with that flashing. Just return needed status and show Error page? 

```
  const { route, error } = useContext()

  //uniqueKey for reload
  let keyForReload = createUnickKey();

  //get data
  const getData = async () => {
    const productId = route.value.params.id
    const data = await getProduct(productId);

    if (!data.status) {
      error({statusCode: data.code, message: data.message })
    }
    return {
      ...data
    }
  }
    
  const productData = useAsync(async () => await getData(), keyForReload)

  return {
    productData: computed(() => productData.value != null ? productData.value : {}),
  }
```

**Comment by ziaadini** [comment]
it will be same issue with nuxt3 too?
