### ISSUE TITLE
help: shallowSsrRef and ssrRef will not hydrate in browser

### ISSUE THREAD

**Issue by stefvw93** [nuxt-community/composition-api#515]
**📚 What are you trying to do? Please describe.**
I'm trying to use `ssrRef` and `shallowSsrRef` outside of the `setup()` hook, in a "global" scope, to hydrate initial state on the client side. However, their states are not hydrated, instead their states are re-set to their defaults. What am I doing wrong?

**🔍 What have you tried?**
I singled out the issue by copying the most basic example from the docs, but this simply does not work for me.

```
// a.ts
export const val = ssrRef(0);
if (process.server) val.value++;

// index.vue
import { val } from "a";

... {
  setup() {
    return { val }
  }
}
```

The server rendered html source contains the updated `1` value, but as soon as the vue app is mounted, the value changes back to `0`.

**Comment by danielroe** [comment]
@stefvw93 If, however, you want to use the global scope, you should know that only changes that happen within a request get serialised. That means changes that happen in a module context won't be reflected. [Here's an example](https://codesandbox.io/s/brave-buck-93t9t?file=/pages/index.vue) of how the global scope could be used.

However, I'd highly recommend only declaring ssrRefs within a setup function so they can be properly associated with an individual request.
