### ISSUE TITLE
fix: useFetch and useMeta together not working

### ISSUE THREAD

**Issue by Mensix** [nuxt-community/composition-api#530]
**🐛 The bug**
When using useMeta hook inside the useFetch, the title value should get updated - which happens just for some miliseconds, then it's reset to the default state.

**🛠️ To reproduce**

1. Go to https://github.com/Mensix/ssr-test and clone the repository
2. Run npm run dev
3. Go to http://localhost:3000/1
4. Notice the bug

**🌈 Expected behaviour**
Title value should be set to as provided in the useFetch hook. Note, that this behaviour worked in some previous versions as expected.

**Comment by danielroe** [comment]
This is the same issue as https://github.com/nuxt-community/composition-api/issues/383. The workaround there may be helpful.

**Comment by Mensix** [comment]
Wop, sorry didn't notice that :) Nevertheless (as mentioned in another similar issue), could it be implemented somewhen? Maybe not even in this package, but in Nuxt 3. My use case is dynamically generated OpenGraph meta tags, and I'm looking forward to have a way for it (I'm currently struggling with undefineds using computed useMeta).
