### ISSUE TITLE
fix: Refs are not automatically shallow unwrapped when accessed in the template

### ISSUE THREAD

**Issue by fabian-hiller** [nuxt-community/composition-api#534]
**🐛 The bug**
 Refs are not automatically shallow unwrapped when accessed in the template. Therefore, the object syntax is rendered in the browser instead of the value.

If I append `.value` to the end it works. However, this is not the expected behavior according to the [Vue 3 documentation](https://v3.vuejs.org/guide/composition-api-setup.html#usage-with-templates). If this is how the behavior is intended for this package, I suggest a note about it in the documentation.

**🛠️ To reproduce**
1. Create a reactive variable  with `ref()` inside `setup()` (e.g. `const myref = ref('hello')`)
2. Return this variable at the end with `return` (e.g. `return { myref }`)
3. Access the reactive variable inside the template (e.g. `<h1>{{ myref }}</h1>`)

**🌈 Expected behaviour**
Automatically shallow unwrapped refs when accessing in template.

**ℹ️ Additional context**
I use TypeScript and `.vue` files.

**Comment by danielroe** [comment]
@fabian-hiller Would you provide a reproduction? You're quite right, it doesn't seem like this falls within [the expected limitations](https://github.com/vuejs/composition-api#limitations).

**Comment by fabian-hiller** [comment]
Hey @danielroe, I'm sorry! I read into the documentation and it was my mistake. In my code it was a nested ref where according to the [documentation](https://v3.vuejs.org/guide/reactivity-fundamentals.html#ref-unwrapping) `.value` is needed.
