### ISSUE TITLE
fix: composition-api breaks storybook build

### ISSUE THREAD

**Issue by Rigo-m** [nuxt-community/composition-api#539]
**🐛 The bug**
Composition-api is breaking storybook build

Posting here as well, but main issue is here: https://github.com/nuxt-community/storybook/issues/318

**Comment by ronmacro** [comment]
Experiencing same issue with vue-layers:

no canvas when '@nuxtjs/composition-api/module' is added to buildModules

**Comment by danieljaywhy** [comment]
@Rigo-m  @ronmacro - have you checked your node version, Node v~14 doesn't work with package.json exports, so upgrading to v15.14.0 worked for me.

**Comment by danielroe** [comment]
@danieljaywhy Note that _some_ older versions of node 12/14 may not work, but the latest node 12/14 should work fine.

**Comment by Rigo-m** [comment]
@danieljaywhy @danielroe tried in my reproduction repo (which you can find in the attached issue), still no luck using node 16. (I have launched these commands: `nvm use node 16 && rm -rf ./node_modules && yarn && yarn storybook:build`)

**Comment by danieljaywhy** [comment]
@Rigo-m have you tried 15.14.0? I found v16 won't work as node/fibres does not support it, this may be local to my machine but we may have similar set ups.

**Comment by Rigo-m** [comment]
I'll try that specific version as soon as I'm back home

**Comment by Rigo-m** [comment]
@danieljaywhy I can confirm the problem affects 15.14.0 as well.
I kind of forgot to post the error in console, which states: ```Failed to generate dynamic story source: TypeError: Cannot read property '_vnode' of null
warn @ vendors~main.be44b584.iframe.bundle.js:2
mounted @ vendors~main.be44b584.iframe.bundle.js:2
invokeWithErrorHandling @ vendors~main.be44b584.iframe.bundle.js:2
callHook @ vendors~main.be44b584.iframe.bundle.js:2
insert @ vendors~main.be44b584.iframe.bundle.js:2
invokeInsertHook @ vendors~main.be44b584.iframe.bundle.js:2
patch @ vendors~main.be44b584.iframe.bundle.js:2
Vue._update @ vendors~main.be44b584.iframe.bundle.js:2
updateComponent @ vendors~main.be44b584.iframe.bundle.js:2
get @ vendors~main.be44b584.iframe.bundle.js:2
Watcher @ vendors~main.be44b584.iframe.bundle.js:2
mountComponent @ vendors~main.be44b584.iframe.bundle.js:2
Vue.$mount @ vendors~main.be44b584.iframe.bundle.js:2
_callee$ @ main.22c25240.iframe.bundle.js:1
tryCatch @ vendors~main.be44b584.iframe.bundle.js:2
invoke @ vendors~main.be44b584.iframe.bundle.js:2
(anonymous) @ vendors~main.be44b584.iframe.bundle.js:2
asyncGeneratorStep @ vendors~main.be44b584.iframe.bundle.js:2
_next @ vendors~main.be44b584.iframe.bundle.js:2
Promise.then (async)
asyncGeneratorStep @ vendors~main.be44b584.iframe.bundle.js:2
_next @ vendors~main.be44b584.iframe.bundle.js:2
(anonymous) @ vendors~main.be44b584.iframe.bundle.js:2
(anonymous) @ vendors~main.be44b584.iframe.bundle.js:2
_render @ main.22c25240.iframe.bundle.js:1
render @ main.22c25240.iframe.bundle.js:1
_callee3$ @ vendors~main.be44b584.iframe.bundle.js:2
tryCatch @ vendors~main.be44b584.iframe.bundle.js:2
invoke @ vendors~main.be44b584.iframe.bundle.js:2
(anonymous) @ vendors~main.be44b584.iframe.bundle.js:2
StoryRenderer_asyncGeneratorStep @ vendors~main.be44b584.iframe.bundle.js:2
_next @ vendors~main.be44b584.iframe.bundle.js:2
Promise.then (async)
StoryRenderer_asyncGeneratorStep @ vendors~main.be44b584.iframe.bundle.js:2
_next @ vendors~main.be44b584.iframe.bundle.js:2
(anonymous) @ vendors~main.be44b584.iframe.bundle.js:2
(anonymous) @ vendors~main.be44b584.iframe.bundle.js:2
renderStory @ vendors~main.be44b584.iframe.bundle.js:2
_callee2$ @ vendors~main.be44b584.iframe.bundle.js:2
tryCatch @ vendors~main.be44b584.iframe.bundle.js:2
invoke @ vendors~main.be44b584.iframe.bundle.js:2
(anonymous) @ vendors~main.be44b584.iframe.bundle.js:2
StoryRenderer_asyncGeneratorStep @ vendors~main.be44b584.iframe.bundle.js:2
_next @ vendors~main.be44b584.iframe.bundle.js:2
(anonymous) @ vendors~main.be44b584.iframe.bundle.js:2
(anonymous) @ vendors~main.be44b584.iframe.bundle.js:2
renderStoryIfChanged @ vendors~main.be44b584.iframe.bundle.js:2
_callee$ @ vendors~main.be44b584.iframe.bundle.js:2
tryCatch @ vendors~main.be44b584.iframe.bundle.js:2
invoke @ vendors~main.be44b584.iframe.bundle.js:2
(anonymous) @ vendors~main.be44b584.iframe.bundle.js:2
StoryRenderer_asyncGeneratorStep @ vendors~main.be44b584.iframe.bundle.js:2
_next @ vendors~main.be44b584.iframe.bundle.js:2
(anonymous) @ vendors~main.be44b584.iframe.bundle.js:2
(anonymous) @ vendors~main.be44b584.iframe.bundle.js:2
renderCurrentStory @ vendors~main.be44b584.iframe.bundle.js:2
(anonymous) @ vendors~main.be44b584.iframe.bundle.js:2
(anonymous) @ vendors~main.be44b584.iframe.bundle.js:2
handleEvent @ vendors~main.be44b584.iframe.bundle.js:2
handler @ vendors~main.be44b584.iframe.bundle.js:2
emit @ vendors~main.be44b584.iframe.bundle.js:2
setSelection @ vendors~main.be44b584.iframe.bundle.js:2
finishConfiguring @ vendors~main.be44b584.iframe.bundle.js:2
ConfigApi.configure @ vendors~main.be44b584.iframe.bundle.js:2
(anonymous) @ vendors~main.be44b584.iframe.bundle.js:2
configure @ main.22c25240.iframe.bundle.js:1
(anonymous) @ main.22c25240.iframe.bundle.js:1
957 @ main.22c25240.iframe.bundle.js:1
__webpack_require__ @ runtime~main.d63247c6.iframe.bundle.js:1
538 @ main.22c25240.iframe.bundle.js:1
__webpack_require__ @ runtime~main.d63247c6.iframe.bundle.js:1
checkDeferredModules @ runtime~main.d63247c6.iframe.bundle.js:1
webpackJsonpCallback @ runtime~main.d63247c6.iframe.bundle.js:1
(anonymous) @ main.22c25240.iframe.bundle.js:1
[...]```

**Comment by ddosdor** [comment]
I have the same problem - the canvas is blank with '@nuxtjs/composition-api/module'. Unfortunately I have no way to verify without this module in 'buildModules' as I already have a finished project. :( 
The problem occurs on both node 14.17.5 and 15.14.0.

`Failed to generate dynamic story source: TypeError: Cannot read properties of null (reading '_vnode')`

**Comment by Rigo-m** [comment]
> I have the same problem - the canvas is blank with '@nuxtjs/composition-api/module'. Unfortunately I have no way to verify without this module in 'buildModules' as I already have a finished project. :(
> The problem occurs on both node 14.17.5 and 15.14.0.
> 
> `Failed to generate dynamic story source: TypeError: Cannot read properties of null (reading '_vnode')`

No need to verify in your project, there is already a reproduction repo attached to this issue: https://github.com/nuxt-community/storybook/issues/318

**Comment by ahmadalfy** [comment]
How does that happen in the build artifact but not in the development mode?

**Comment by Rigo-m** [comment]
> How does that happen in the build artifact but not in the development mode?

It is probably because of how things get stitched together by webpack or something that happens within the storybook build routine. I don't see how this question helps btw.

**Comment by ahmadalfy** [comment]
>  I don't see how this question helps btw.

I am just asking because I am new to Nuxt and Vue and thought of investigating how that could be fixed. There is a lot of stuff that Nuxt hides and a lot of magic happening in the background. Think of it as an innocent question from someone who wants to help.

**Comment by ahmadalfy** [comment]
OK I am digging into this and the problem seems to be even bigger. The current repository when cloned and you run the command `yarn test`, the produced static storybook artifact doesn't even work because of the modules added to nuxt.

If we remove the `@nuxtjs/color-mode` from the `buildModules` in `nuxt.config.js`, it works fine. So this behavior isn't exclusive to the composition API, it might be happening with different other modules added to the `buildModule`.

I will keep digging and post updates.

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt-community/composition-api/pull/578
