### ISSUE TITLE
help: 

### ISSUE THREAD

**Issue by ikamez** [nuxt-community/composition-api#544]
I'm trying to install this package but I got this error 
"Package subpath './dist/vue-composition-api.esm.js' is not defined"

Yarn : 1.22.11
Nuxt : 2.15.7
@nuxtjs/composition-api: 0.28.0  

Please help.

**Comment by xxyqyq** [comment]
I have the same problem
node： 14.12.0
@nuxtjs/composition-api: 0.28.0
nuxt: 2.15.8
npm : 6.14.8

**Comment by xxyqyq** [comment]
Solved after updating the node version, this 14.12.0 version does not support the new features

**Comment by ikamez** [comment]
@xxyqyq 

Which node version that you use now ?

**Comment by xxyqyq** [comment]
14.17.6

**Comment by ikamez** [comment]
This issue solved
