### ISSUE TITLE
fix: useAsync called one time for dynamic URL in SSR mode

### ISSUE THREAD

**Issue by barikhan1986** [nuxt-community/composition-api#545]
**🐛 The bug**
useAsync called one time for dynamic URL in SSR mode

**🛠️ To reproduce**

1- add dynamic page : category/_id.vue
2- in _id.vue add links like:
```
   <Nuxt-Link :to="'category/1'">category 1</Nuxt-Link>
   <Nuxt-Link :to="'category/2'">category 2</Nuxt-Link>
   <Nuxt-Link :to="'category/3'">category 3</Nuxt-Link>
```

3- in _id.vue add :
` const categoryDetails =  useAsync(() => categoryDetails(categoryId))`
to fetch category data in server

4- Now open IP::PORT/category/1, useAsync will working fine

5- click in "category 2" anchor, URL will change in browser, but useAsync will not calling again and keep old value for categoryDetails variable!!

if you open Home Page IP::PORT/ directly and navigate to category/1 and click in category/2, useAsync will calling and fetch data for category 2, there is no issue. 
the issue happens only when you open category page in SSR mode and navigate to the same category page with different id.

for fixing this issue temporary, I did the following:

```
onBeforeMount(async () => {
     if( (categoryId.value && categoryId.value!=route.value.params.categoryId)
    {
       categoryDetails.value=null
       categoryDetails.value = categoryDetails(categoryId)
    }
 })
```

**Comment by danielroe** [comment]
@barikhan1986 This is by design. You can pass a 'key' to `useAsync` that is based on the slug if you want what it has cached to vary based on the slug.

See https://github.com/nuxt-community/composition-api/issues/171 for more discussion.
