### ISSUE TITLE
fix: `<script setup>` does not fully support pug template

### ISSUE THREAD

**Issue by flavionn** [nuxt-community/composition-api#546]
Hello

im trying to use getter and script setup in my SFC

```vue
<script setup>

import { useStore, computed } from '@nuxtjs/composition-api'

const store = useStore()
const isLoggedIn = computed(() => store.getters['users/isLoggedIn'])

</script>
```

and in my template i have:

```pug
template(v-if="isLoggedIn")
```

but im getting this:

```console
[Vue warn]: Property or method "isLoggedIn" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property.
```

ps - console.log(isLoggedIn) is returning correct result from getter

"@nuxtjs/composition-api": "0.28.0"
"nuxt": "2.15.8"
"nuxt-vite": "0.2.4"

**Comment by danielroe** [comment]
Seems to work fine for me with normal HTML template: https://codesandbox.io/s/green-forest-1siz9?file=/pages/index.vue

Perhaps you could see if that makes a difference for you, or if not, provide a reproduction? 🙏

**Comment by flavionn** [comment]
thanks for reply, im trying to work in a reproduction. for now the only diference i saw in your example was the store. im using in a folder structure.

like this:
<code>store > users > getters.js</code>
```js
export default {
  isLoggedIn(state) {
    return !!state.currentUser
  }
}
```

**Comment by antfu** [comment]
vue2-script-setup does not support pug atm, please open an issue there instead and PR is also welcome!

**Comment by antfu** [comment]
Supported in v0.6.1

**Comment by flavionn** [comment]
hello! just one more question in here.

it is possible use unplugin-vue2-script-setup version 0.6.1 while nuxtjs composition api is not updated with this version?

i tried put unplugin-vue2-script-setup in resolutions in my `package.json` but got this message 

```bash
[plugin:unplugin-vue2-script-setup] Unexpected token, expected "," (1:16)
```

**Comment by danielroe** [comment]
@flavionn Yes, it should be possible - even just running `yarn upgrade unplugin-vue2-script-setup` should do the trick.
