### ISSUE TITLE
fix: ERR_PACKAGE_PATH_NOT_EXPORTED with @nuxtjs/composition-api

### ISSUE THREAD

**Issue by adamberecz** [nuxt-community/composition-api#548]
**🐛 The bug**
Getting the following error with a fresh install and `@nuxtjs/composition-api`:

```
✖ Nuxt Fatal Error

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/vue-composition-api.esm.js' is not defined by "exports" in .../node_modules/@vue/composition-api/package.json 
```

**🛠️ To reproduce**

- Install a fresh nuxt with npm
- Install `@nuxtjs/composition-api`
- Add to build modules:
``` js
{
  buildModules: [
    '@nuxtjs/composition-api/module'
  ]
}
```
- Hit `npm run dev`

**🌈 Expected behaviour**
Nuxt app starts without an error.

**ℹ️ Additional context**
```
Nuxt @ v2.15.8
▸ Environment: development
▸ Rendering:   server-side
▸ Target:      server
```

npm version: 6.14.4
node version: 14.1.0
The app starts properly without enabling the module.

**Comment by danielroe** [comment]
@adamberecz Try upgrading your version of node 14. ☺️

**Comment by adamberecz** [comment]
🙏
