### ISSUE TITLE
fix: [Vue warn]: toRefs() expects a reactive object but received a plain one.

### ISSUE THREAD

**Issue by thisVioletHydra** [nuxt-community/composition-api#555]
**🐛 The bug**
What isn't working? Describe what the bug is.

**🛠️ To reproduce**

run nuxt
add https://pinia.esm.dev/ssr/nuxt.html
import store like 

```ts
<!-- SCRIPT -->
<script lang="ts">
  import { defineComponent } from '@nuxtjs/composition-api'; 
  import { useStore } from "~/store/main";

  export default defineComponent({
    name: 'Count',
    props: {},
     setup() {
        const store = useStore();
        return { store };
    }
  });
</script>
<!-- - ⚡ - -->


```
store: 
```ts
import { defineStore } from 'pinia';

export const useStore = defineStore('companiesInfo', {
  state: () => ({
    data: {test: 1},
  }),
});

```

I'd be very grateful for a link to a gist or repo that reproduces the bug.

**🌈 Expected behaviour**
What did you expect to happen? Is there a section in the docs about this?

**ℹ️ Additional context**
pinia issues 
https://github.com/posva/pinia/issues/648

**Comment by danielroe** [comment]
@thisVioletHydra Would you provide a reproduction via https://template.nuxtjs.org ? 🙏

**Comment by thisVioletHydra** [comment]
> @thisVioletHydra Would you provide a reproduction via https://template.nuxtjs.org ? 🙏

okay no problem

**Comment by thisVioletHydra** [comment]
> @thisVioletHydra Would you provide a reproduction via https://template.nuxtjs.org ? 🙏

https://codesandbox.io/s/weathered-bird-l4kww?file=/components/Test.vue
push refresh page 
![image](https://user-images.githubusercontent.com/11839238/133751302-280f05d5-bc58-4867-ab6c-be7825f7d2e1.png)
![image](https://user-images.githubusercontent.com/11839238/133751315-b0c002ca-f8e5-4a75-b093-7516dcb69741.png)

**Comment by thisVioletHydra** [comment]
@danielroe any news ?

**Comment by posva** [comment]
The error comes from https://github.com/vuejs/composition-api/pull/821
