### ISSUE TITLE
fix: Build failing with node 16

### ISSUE THREAD

**Issue by kirtan403** [nuxt-community/composition-api#558]
**🐛 The bug**
create-nuxt-app with just adding composition api is not working. Giving the following error:

![image](https://user-images.githubusercontent.com/7900938/134691779-adcb1561-f705-4333-83b8-d94e02191de1.png)

Node version for the above screenshot: `v16.10.0`

When using with node `v14.5.0`, giving me the following error:
![image](https://user-images.githubusercontent.com/7900938/134692549-88586dd6-575b-49ed-94cb-f2fa8c7d8afb.png)

**🛠️ Reproduction repo: **
https://gitlab.com/kirtan403/nuxt-composition-error-node16/

**🌈 Expected behaviour**
It should run without any errors.

**Comment by kirtan403** [comment]
@danielroe Switched to Node v14.17.6 (Latest LTS). Still the same issue.

**Comment by kirtan403** [comment]
Giving the same error as in v16. 

![image](https://user-images.githubusercontent.com/7900938/134709741-9a6b09cd-2f85-48ec-b70e-2b230c9e99c8.png)

**Comment by danielroe** [comment]
@kirtan403 Would you confirm whether it occurs without `@nuxtjs/composition-api`? I would also suggest removing your `node_modules` and reinstalling - or perhaps even refreshing your lockfile entirely.

**Comment by kirtan403** [comment]
@danielroe It worked. Deleting `node_modules` and lock file helped. It worked on latest `v14` of the node. But on the `v16` it is not working. Should I keep it open for that or close the issue?

**Comment by danielroe** [comment]
If you're still experiencing this, let me know and I can reopen.
