### ISSUE TITLE
Broken types starting from version 0.25.1

### ISSUE THREAD

**Issue by P4sca1** [nuxt-community/composition-api#562]
**🐛 The bug**
unreferenced refs to `Date` or `Timeout` objects are no longer assignable to `Date` and `Timeout`. The problem might exist for other types too.

```
Argument of type '{ toString: () => string; toDateString: () => string; toTimeString: () => string; toLocaleString: { (): string; (locales?: string | string[] | undefined, options?: DateTimeFormatOptions | undefined): string; }; ... 38 more ...; toJSON: (key?: any) => string; }' is not assignable to parameter of type 'Date'.
  Property '[Symbol.toPrimitive]' is missing in type '{ toString: () => string; toDateString: () => string; toTimeString: () => string; toLocaleString: { (): string; (locales?: string | string[] | undefined, options?: DateTimeFormatOptions | undefined): string; }; ... 38 more ...; toJSON: (key?: any) => string; }' but required in type 'Date'.
```

**🛠️ To reproduce**
```ts
function useCurrentTime() {
  // Simplified for reproduction
  return ref(new Date())
}

function printDate(date: Date) {
  console.log(date.toLocaleString())
}

// In setup
const currentTime = useCurrentTime()
printDate(currentTime.value) // Get above error
```

**ℹ️ Additional context**
Version 0.25.0 works fine. Every more recent version, starting from version 0.25.1, has this problem.

I found the following related issue: https://github.com/vuejs/vue-next/issues/4307
Upgrading to TypeScript 4.3 seems to have fixed the issue, but that is not possible with nuxt currently, as it only works with TypeScript versions up to 4.2.

**Comment by danielroe** [comment]
@jankaderabek This is likely an issue with your TypeScript version, as indicated in the issue you linked: https://github.com/vuejs/vue-next/issues/4307#issuecomment-903093931. Could you try with a newer version?

**Comment by valh1996** [comment]
@danielroe I'm sorry, but I'm not sure I understand your answer knowing that the first comment says this:
```
Upgrading to TypeScript 4.3 seems to have fixed the issue, but that is not possible with nuxt currently, 
as it only works with TypeScript versions up to 4.2.
```
**Why is this not possible with Nuxt? Using a more recent version of Typescript could cause problems in Nuxt?**

However, adding `"typescript": "4.5.2"` (latest version available atm) to the `dependencies` of the `package.json` fix de problem. Is it a viable solution or should I set a resolution like this?:
```
"resolutions": {
  "typescript": "^4.5.2"
},
```
I just want to make sure that doing this won't cause trouble elsewhere with Nuxt.

Thank you for your eventual reply and congratulations for your work on Nuxt!

**Comment by danielroe** [comment]
@valh1996 Yes, it should certainly be possible to use Nuxt with newer TypeScript versions - and yes, I think using a resolution is a reasonable solution. 👍

**Comment by valh1996** [comment]
> @valh1996 Yes, it should certainly be possible to use Nuxt with newer TypeScript versions - and yes, I think using a resolution is a reasonable solution. 👍

Great, thanks for your quick response. But concretely, where would we have to fix this version to make it work out of the box? I imagine that other people have the same problem...
