### ISSUE TITLE
fix: TypeError: (0 , _compositionApi.defineComponent) is not a function

### ISSUE THREAD

**Issue by viennv1709** [nuxt-community/composition-api#569]
**🐛 The bug**
I'm running the tests with jest. And I said: TypeError: (0 , _compositionApi.defineComponent) is not a function

**🛠️ To reproduce**
![image](https://user-images.githubusercontent.com/5088270/137875021-a0f77434-fba0-4362-8741-31cec6f9e240.png)

**🌈 Expected behaviour**
Improve docs for testing

**ℹ️ Additional context**
nuxt: 2.15.7
@nuxtjs/composition-api: 0.29.3

**Comment by danielroe** [comment]
@viennv1709 Would you try removing that line from your `jest.config.js`? It shouldn't be required, and it is certainly pointing at the wrong location.
