### ISSUE TITLE
help: useAsync with provide/inject

### ISSUE THREAD

**Issue by zipme** [nuxt-community/composition-api#580]
**📚 What are you trying to do? Please describe.**
I am trying to pass async data to layout from a page component. 

**🔍 What have you tried?**
```vue
// layout/default.vue
<template>
  {{ data }} // this works fine on client side but not on server side (view source code shows nothing here)
</template>
<script>
setup() {
  const data = ref(null)
  const setData = (val) => (data.value = val)

  provide('data', {
    data,
    setData: readonly(data),
  })
}
</script>
```
```vue
// pages/foo.vue
<script>
setup() {
 const { setData } =  inject('data')
  const result = useAsync(async () => { 
    const data = await fetch(...)
    setData(data)
    return data
  })
}
<script>
```

**ℹ️ Additional context**
The only way I can get this to work is by using `store`, which is what I try to avoid in this (small) project
e

**Comment by og-neth** [comment]
@zipme when you inject in your component, is `setData` undefined or is it properly set? I am having an issue where when I inject from my layout.vue into a footer component, I am getting undefined when I inject... using vue 2 with composition-api in nuxt 2 project.

**Comment by danielroe** [comment]
`useAsync` should not have side effects. Also, passing data from a component up to a layout will always lead to hydration issues if you are doing server-side rendering.
