### ISSUE TITLE
feat: setup will be executed twice

### ISSUE THREAD

**Issue by Vi-jay** [nuxt-community/composition-api#581]
It will be executed once when the page is rendered from the server, and then again when the page is rendered for the client. Could it be similar to the fetch function? The client does not repeat the fetch function when the page is rendered on the server side.

**Comment by danielroe** [comment]
That's how `setup()` is meant to work. Think of it like the `created()` lifecycle hook.

**Comment by Vi-jay** [comment]
> That's how `setup()` is meant to work. Think of it like the `created()` lifecycle hook.

But we have already fetched the data once when rendering on the server side, and requesting it again on the client side is a meaningless consumption.  For example, the fetch method of nuxt will not perform an additional meaningless request on the client side.

**Comment by danielroe** [comment]
@Vi-jay `setup()` is not for fetching data. Instead it is for calling helpers and exposing values to the template. You might find [these docs](https://v3.vuejs.org/guide/composition-api-introduction.html) helpful to read.

**Comment by Vi-jay** [comment]
> @Vi-jay `setup()` is not for fetching data. Instead it is for calling helpers and exposing values to the template. You might find [these docs](https://v3.vuejs.org/guide/composition-api-introduction.html) helpful to read.

Sorry, I found my mistake. Specifically, instead of `setup` being executed twice, `useFetch` being executed twice,
For `setup`, it should be executed twice because it is a life cycle function similar to `created`. When the `useFetch` hook is executed, a fetch has been executed, but I will `useFetch`
The returned `fetch` function was executed again, resulting in two fetches.
Sorry for wasting your time
Like on the document
```ts
const { fetch, fetchState } = useFetch(async () => {
  name.value = await axios.get('https://myapi.com/name')
})

// Manually trigger a refetch
// I misunderstood the meaning of this comment
fetch()
```
