### ISSUE TITLE
help: Start my nuxt project without Composition-API

### ISSUE THREAD

**Issue by evanlegamer** [nuxt-community/composition-api#582]
**📚 What are you trying to do? Please describe.**

Start my project with 
```
npm run dev
```

**🔍 What have you tried?**

I added @nuxtjs/composition-api to my project through a basic 
```
npm i @nuxtjs/composition-api
```

then i finaly do not want to use it so i did
```
npm uninstall @nuxtjs/composition-api
```

and delete all occurence of this in my project.

but i get this error now

<img width="1079" alt="Capture d’écran 2021-11-10 125324" src="https://user-images.githubusercontent.com/18480367/141108406-4641e2a1-9028-4478-b2ce-ac46a75bb410.png">

I did npm clear cache, i delete node_modules and try npm i. Then i deleted my project, i reclone it form git but same thing happen over and over... 

**ℹ️ Additional context**

I tried to find any occurence of this in my project but there is no one.

Since none of my depencencies needs this package, it's even not in the node_modules.

My package.json

```js
{
        "name": "test",
	"private": true,
	"scripts": {
		"dev": "nuxt",
		"build": "nuxt build --modern",
		"start": "nuxt start",
		"generate": "nuxt generate",
		"lint": "eslint --ext .js,.vue --ignore-path .gitignore ."
	},
	"dependencies": {
		"@mollie/api-client": "^3.2.4",
		"@nuxtjs/apollo": "^4.0.1-rc.4",
		"@nuxtjs/axios": "^5.10.3",
		"@nuxtjs/proxy": "^1.3.3",
		"@nuxtjs/pwa": "^3.0.0-beta.20",
		"@nuxtjs/snipcart": "^1.2.2",
		"@nuxtjs/svg-sprite": "^0.4.10",
		"@tailwindcss/forms": "^0.3.3",
		"@vue/apollo-composable": "^4.0.0-alpha.15",
		"@vue/composition-api": "^1.3.3",
		"apollo-boost": "^0.4.9",
		"babel-plugin-transform-runtime": "^6.23.0",
		"core-js": "^3.16.0",
		"graphql": "^15.3.0",
		"graphql-tag": "^2.10.3",
		"img-vuer": "^0.19.2",
		"nanoid": "^2.1.11",
		"nuxt": "^2.15.8",
		"regenerator-runtime": "^0.13.9",
		"vue": "^2.6.11",
		"vue-cleave-component": "^2.1.3",
		"vue-google-oauth2": "^1.5.5",
		"vue-grid-layout": "^2.3.11",
		"vue-plausible": "^1.2.1",
		"vue2-filters": "^0.11.0",
		"vuedraggable": "^2.24.3",
		"vuex-persistedstate": "^2.7.1"
	},
	"devDependencies": {
		"@nuxtjs/eslint-config": "^1.0.1",
		"@nuxtjs/eslint-module": "^1.2.0",
		"@nuxtjs/tailwindcss": "^4.0.3",
		"babel-eslint": "^10.1.0",
		"case-sensitive-paths-webpack-plugin": "^2.3.0",
		"eslint": "^6.8.0",
		"eslint-plugin-nuxt": "^1.0.0",
		"postcss": "^8.2.13"
	}
}
```

**Comment by danielroe** [comment]
It's possible you have another module which is installing this one, or of course you might still have a mention of it in your `nuxt.config` which has escaped your notice?
