### ISSUE TITLE
bug: Template Refs don't work in render functions

### ISSUE THREAD

**Issue by jonashe** [nuxt-community/composition-api#588]
**🐛 The bug**
Template Refs in Render Functions don't work with nuxt-composition-api

**🛠️ To reproduce**

1. Create a component with some markup returned by a render function
2. Assign a ref to one of the elements
1. I created a minimal working example: https://codesandbox.io/s/suspicious-easley-sxwmx?file=/pages/index.vue

**🌈 Expected behaviour**
In the preview window `My template ref is [object HTMLDivElement]` should be shown, however `My template ref is undefined` is shown

**ℹ️ Additional context**
For comparison, I created the same example using the vue-composition-api: https://codesandbox.io/s/compassionate-chaum-h9gjl?file=/src/App.vue

**Comment by danielroe** [comment]
The latest version of nuxt/composition-api directly exports from render behaviour from vue itself. Would you check with the latest version to see if this is still an issue? 🙏

**Comment by rchl** [comment]
Closing due to no response from the reporter for almost a year.
