### ISSUE TITLE
fix: using useFetch page header HTTP status code doesn't return 404 but always 200

### ISSUE THREAD

**Issue by jnralava** [nuxt-community/composition-api#594]
**🐛 The bug**
when i try to access a bad id, the api returns a 404 error, but the page HTTP status code is still 200.
```
Error in fetch(): { HTTPError: Not Found
    at fn (server.js:4440:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'HTTPError',
  response:
   Response {
     size: 0,
     timeout: 0,
     text: [Function],
     json: [Function],
     data: {},
     [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
     [Symbol(Response internals)]:
      { url: 'https://jsonplaceholder.typicode.com/posts/404',
        status: 404,
        statusText: 'Not Found',
        headers: [Headers],
        counter: 0 } },
  statusCode: 404 }
eval @ client.js?06a0:56

```

**🛠️ To reproduce**

1. Go to '[useFetch official doc](https://composition-api.nuxtjs.org/examples/useFetch)'
2. Run the project example
3. Click on '[404 post](https://4wnkz.sse.codesandbox.io/posts/404)'
4. See console error

**Comment by danielroe** [comment]
This is how the `fetch()` hook works in Nuxt 2, and is due to a limitation of `serverPrefetch` which is being used under the hood. You'll need to handle the error yourself by inspecting the error property that is returned from `useFetch`. Any redirect needs to be done on client side.
