### ISSUE TITLE
help: Wait for promise to resolve before client side rendering.

### ISSUE THREAD

**Issue by arsy29** [nuxt-community/composition-api#596]
**📚 What are you trying to do? Please describe.**
Is there a way to wait for API calls or any promise to resolve before loading the page so that it would include details from the API.

**🔍 What have you tried?**
I tried using useAsync, useFetch, onServerPrefetch but have a problem with redirecting and reloading pages where data is available in some cases, and some render the page blank and just wait for the promise to finish and render the details.

**ℹ️ Additional context**
I'm creating a landing page where details such as title, images and etc. are being supplied using API.

**Comment by danielroe** [comment]
At the moment, we can't block page navigation on client-side using the composition API + Nuxt 2.

On server-side, `useFetch` or `onServerPrefetch` should work to block page load on the initial SSR. Perhaps you could share your code if you're finding it's not working for you.
