### ISSUE TITLE
help: Does @nuxtjs/composition-api work on IE11 ?

### ISSUE THREAD

**Issue by Nealll68** [nuxt-community/composition-api#614]
Hello,

**📚 What are you trying to do? Please describe.**
I would like to make @nuxtjs/composition-api work on IE11 but in the console i received some script errors : 
![image](https://user-images.githubusercontent.com/19308795/156330000-457612a5-1059-4a21-99dc-c4a0f409998a.png)

It say that a const must be initialized and a parenthesis is missing

**🔍 What have you tried?**
Tried to transpile package, other versions, include polyfill

**ℹ️ Additional context**
I added @nuxtjs/composition-api on a fresh initialized nuxt project, when a remove this package i have no more errors. If i just import @vue/composition-api as a plugin i don't have errors too

Thanks!

**Comment by danielroe** [comment]
Try adding `defu` and `ufo` to your `build.transpile` array. Those are the only runtime dependencies of this module, and the module itself is already transpiled. Failing that, check the code referenced in your above screenshot and see if you can identify what module it comes from.

**Comment by Nealll68** [comment]
Adding `defu` and `ufo` in transpile doesn't resolve the problem but when I search in the console I see that it come from defu for the missing parenthesis : 
![image](https://user-images.githubusercontent.com/19308795/156393095-75488dfb-422a-4f32-889c-40b95ffebec2.png)

And for the "const must be initialized" it come from this code : 
![image](https://user-images.githubusercontent.com/19308795/156393200-0ce1267a-474a-4a8b-b51d-801594a8b21d.png)

Thanks for the help anyway, i will try some other things to resolve this. We are on a monorepo structure with yarn workspaces, maybe there are some conflicts with other packages

**Comment by Nealll68** [comment]
Hi,

for information I resolved all errors by forcing defu & ufo version in my package.json with yarn :
```
"resolutions": {
    "defu": "4.0.1",
    "ufo": "0.6"
  }
```
Actually, I don't have side effects by downgrading theses packages
