### ISSUE TITLE
useFetch does not work with nested _slug pages

### ISSUE THREAD

**Issue by P4sca1** [nuxt-community/composition-api#618]
**🐛 The bug**
When you have the following directory structure:
* `/_slug.vue`
* `/_slug/page.vue`

and `useFetch` in both pages, it will not work correctly.

**🛠️ To reproduce**

1. Visit https://codesandbox.io/s/goofy-murdock-obbijt?file=/pages/_id/test.vue
2. Click on 'To Reproduction'. You should see a list of todos.
3. Reload the browser. You should see the same list of todos for a short time but then it should disappear and `todos.value` becomes `null`.

**🌈 Expected behaviour**
`useFetch` should work with nested _slug pages.

**ℹ️ Additional context**
When you comment out the `useFetch` block in `_id.vue`, the issue disappears.

**Comment by danielroe** [comment]
This is an issue not with the composition API module but with how fetch is implemented in Nuxt 2. In short, it adds a fetch key to the rendered HTML element to match it up to the payload. But in your case, the element for each of these pages is the same, so it breaks it. Add a wrapper element and you'll find it will work.

**Comment by P4sca1** [comment]
Thank you very much for the hint!
Adding a wrapping `<div>` around `<nuxt-child />` indeed fixed the issue.
