### ISSUE TITLE
Cant install composition api in Nuxt 2

### ISSUE THREAD

**Issue by avarvouzou** [nuxt-community/composition-api#620]
**🐛 The bug**
I have a Nuxt 2.15.8 app and I would like to use nuxt/composition-api, but when i'm trying to build the app, it failed on the following error:

![image](https://user-images.githubusercontent.com/76907288/159023688-7a430a42-f0a8-4f94-a245-a339fa612221.png)
**🛠️ To reproduce**
It was after i followed all the steps here to install composition api ---> https://composition-api.nuxtjs.org/

same as https://github.com/nuxt-community/composition-api/issues/190

**Comment by dncdrn** [comment]
Hi @danielroe @avarvouzou I have the same error after installing the composition api for vue echarts. I followed the steps from this docu https://github.com/ecomfe/vue-echarts

**Comment by danielroe** [comment]
Would you provide a reproduction please?

**Comment by rchl** [comment]
Closing as no reproduction was provided in almost a year.
