### ISSUE TITLE
fix: fetchKey not being set properly affecting useFetch

### ISSUE THREAD

**Issue by ttonyh** [nuxt-community/composition-api#633]
**🐛 The bug**
useFetch is not able to handle multiple requests on a single load, due a fetchKey issue. fetchKey is not being set properly when the module runs. The composition-api module is being added to buildModules like the docs state. This problem seems to go away when I move the module to "modules" (but causes other problems).

Here is the line of code that prevents the key to set:
```
https://github.com/nuxt-community/composition-api/blob/main/src/runtime/composables/fetch.ts#L315
```
When debugging in Node and breakpoint is applied to above line, "process.server" is "undefined".

This is what the ```__NUXT__``` global object looks like after page has loaded:

![2022-05-03_19-08](https://user-images.githubusercontent.com/1578211/166616274-ad202495-a848-42fa-a8da-7c21c0442f51.png)

**🛠️ To reproduce**

1. Run Nuxt in "server" mode, add component-api to buildModules
2. Create a component that uses "useFetch" to make an async call.
3. Open dev console and inspect __NUXT__.fetch
4. See "NaN" property instead of component name (or proper key) (see above screenshot)

**🌈 Expected behaviour**
```__NUXT__.fetch``` should show proper fetch keys instead of "NaN"

**ℹ️ Additional context**
This is due to "getKey" not being called because "process.server" is undefined. (see runtime/composables/fetch.ts#L315)

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏
