### ISSUE TITLE
fix: calling `context.error()` inside useFetch causes a vnode mismatch?

### ISSUE THREAD

**Issue by DEV-ONI** [nuxt-community/composition-api#635]
**🐛 The bug**
Calling `context.error()` inside useFetch shows the error page but causes a vnode mismatch.
Am I doing something wrong or missing something?

![image](https://user-images.githubusercontent.com/52248548/169457081-a087b40d-79bb-4847-bf00-96e8261d397f.png)

**🛠️ To reproduce**
Call `context.error()` inside `useFetch()`;

**ℹ️ Additional context**

Example code:

```vue
            const context = useContext();
            const route =  useRoute();  
            const storyDir = stripStartSlash(route.value.path);

            const { story, fetchStory }  = useStory(route.value.path);
            const { fetch, fetchState } = useFetch(async() => {
                
                try {
                     await fetchStory();
                } catch(err) {
                   context.error({ statusCode: error.response.status })
                }               
               
            })
```

**Comment by danielroe** [comment]
The fetch hook in Nuxt 2 is not compatible with context.error and you should instead use the error properly on the fetch state to handle any errors within the component using fetch.
