### ISSUE TITLE
fix: useAsync is not running correctly

### ISSUE THREAD

**Issue by josuemartinezz** [nuxt-community/composition-api#637]
**🐛 The bug**
When `useAsync` is used in our code, full resolution is expected on the server side, regardless of whether the page loaded where `useAsync` is used or when it is navigated. But when navigating it breaks completely, that is, the endpoint is loaded when the user navigates to the view and does not wait for the resolution of the promise, this behavior makes it impossible to find objects or information that you want to show in the view, for the simple fact that the promise to change the page has not yet been fulfilled 😭

**🛠️ To reproduce**

- Use the useAsync api just as found in the documentation:
```
import { defineComponent, useAsync, useContext } from '@nuxtjs/composition-api'

export default defineComponent({
  setup() {
    const { $http } = useContext()
    const posts = useAsync(() => $http.$get("pages/home"))

    return { posts }
  },
})
```
Reload is done on the same page, the desired result is expected (load on the server)
- Now, if you're on another page and you want to navigate to the page where you use useAsync, it breaks completely.

**🌈 Expected behaviour**
The expected result is a completely server-side call

**ℹ️ Additional context**
In order to solve this impersistence I have been occupying `asyncData` inside my `defineComponent`, as follows:

```
export default defineComponent({
  name: 'IndexPage',
  asyncData({ $axios }) {
    return $axios.$get("pages/home");
  },
});
```

This fully achieves the desired result, but without using what's new in `vue 3`

**Comment by danielroe** [comment]
I'm afraid this is a limitation of Vue 2, which is what this module is using. (It's not possible to block client-side navigation with a composable.)
