### ISSUE TITLE
fix: useMeta() throws error if used in a layout

### ISSUE THREAD

**Issue by miii** [nuxt-community/composition-api#64]
**🐛 The bug**
The `head: {}` property triggers an error inside `@vue/composition-api` if used in a layout component, thus `useMeta()` cannot be used.
```
[vue-composition-api] must call Vue.use(plugin) before using any function
```

Pages seems to work as expected. The problem is caused by `reactive()` not being used in the correct scope (too soon in the Nuxt lifecycle?).
https://github.com/nuxt-community/composition-api/blob/48547f0a21ea6165f7f1df3569cc6b4dc54cad92/src/meta.ts#L43-L53

I've resolved the issue myself in a fork by using `Vue.observable()` instead of `reactive()`.
I'll submit a PR when it's ready to be reviewed.

**🛠️ To reproduce**

1. Add `head: {}` to your layout
2. See error

Use this sandbox to reproduce the error.
https://codesandbox.io/s/nuxt-composition-api-usemeta-layout-issue-r14yy?file=/layouts/default.vue

**🌈 Expected behaviour**
`useMeta()` should work in layout components as expected.

**Comment by danielroe** [comment]
@miii I really appreciate this bug report and the associated PR. I think the issue is bigger than just `useMeta`, however - as nothing Composition API-related could be used in layouts. If we just solve the `useMeta` issue, the bigger problem remains. So I'm deploying a fix. Do let me know if it doesn't fix the error, however.

**Comment by Mikaleb** [comment]
Error is not closed at all, can still reproduce with last version : 

layouts/default.vue
```
export default defineComponent({
  name: 'ContentLayout',
setup(props, ctx) {

    const { title } = useMeta()
    title.value = 'Test'
    return {title}
}
```

Getting useMeta must be called within a component.

**Comment by danielroe** [comment]
@Mikaleb Would you mind providing a reproduction?

**Comment by Mikaleb** [comment]
@danielroe I tried and saw that my version was not updated for some reason, my apologies !
