### ISSUE TITLE
Can't install @nuxtjs/composition-api anymore

### ISSUE THREAD

**Issue by ThinkingAbout** [nuxt-community/composition-api#644]
I can't install the composition api package anymore on fresh nuxt projects.

I've just created a new blank nuxt project with `npm init nuxt-app my-project-name` and and immediately after I installed `@nuxtjs/composition-api` using npm and following the steps in the [docs](https://composition-api.nuxtjs.org/getting-started/setup).

I get the following error:  

```
Vue packages version mismatch:
  
  - vue@2.6.14
  - vue-server-renderer@2.7.1
  
  This may cause things to work incorrectly. Make sure to use the same version for both.
```

![Schermata 2022-07-04 alle 16 00 16](https://user-images.githubusercontent.com/682778/177170218-e4b7b831-87fa-4402-957a-cb96a3468902.png)

- OS: MacOs Monteray 12.4
- node -v v16.15.1
- npm -v 8.11.0

Can somebody help please?

Matteo

**Comment by ThinkingAbout** [comment]
It looks like that the problem also occurs in previous projects by deleting the package-lock file and running npm install again.
Thanks,
Matteo

**Comment by vahid-bagh3ri** [comment]
> I can't install the composition api package anymore on fresh nuxt projects.
> 
> I've just created a new blank nuxt project with `npm init nuxt-app my-project-name` and and immediately after I installed `@nuxtjs/composition-api` using npm and following the steps in the [docs](https://composition-api.nuxtjs.org/getting-started/setup).
> 
> I get the following error:
> 
> ```
> Vue packages version mismatch:
>   
>   - vue@2.6.14
>   - vue-server-renderer@2.7.1
>   
>   This may cause things to work incorrectly. Make sure to use the same version for both.
> ```
> 
> ![Schermata 2022-07-04 alle 16 00 16](https://user-images.githubusercontent.com/682778/177170218-e4b7b831-87fa-4402-957a-cb96a3468902.png)
> 
> * OS: MacOs Monteray 12.4
> * node -v v16.15.1
> * npm -v 8.11.0
> 
> Can somebody help please?
> 
> Matteo

I have The Same Problem too :(

**Comment by danielroe** [comment]
This is an issue with your specific package manager and lockfile situation, and on every Vue upgrade there are often mismatches which people need to resolve by updating their lockfiles and/or explicitly installing the right version of Vue packages. But it is not an issue with `@nuxtjs/composition-api`. In fact, this library has no explicit vue or vue-server-renderer dependencies.

Here's an example working fine with the latest Nuxt 2.15.8 and Composition API: https://stackblitz.com/edit/github-4nyzv3.

**Comment by ThinkingAbout** [comment]
@bobbyadamski with 2.6.14 I was able to run the project again.
@danielroe I tried with 2.7 but same error occured, am I doing something wrong?

[https://stackblitz.com/edit/github-4nyzv3-zdknmq?file=package.json](https://stackblitz.com/edit/github-4nyzv3-zdknmq?file=package.json)

Thanks

**Comment by Jozaguts** [comment]
I had the same problem, and I was "fix it" with: 
- removing "^" in these 2 packages:
    - "vue-server-renderer": "2.6.14",
     - "vue-template-compiler": "2.6.14"

Delete 
-  package-lock.json 
-  node_modules

run npm install

and now I have this message

>  Nuxt Bridge has now been released in beta. It has full composition API support and it's strongly recommended to migrate from @nuxtjs/composition-api, if possible
, by following the steps at https://v3.nuxtjs.org/getting-started/bridge. Feedback welcome at https://github.com/nuxt-community/composition-api/discussions/585.   
```
i Waiting for file changes                                                                                                                              
i Memory usage: 376 MB (RSS: 468 MB)                                                                                                                    
i Listening on: http://localhost:3000/                                                                                                                  
No issues found.```

I hope this helps you!

**Comment by ThinkingAbout** [comment]
@Jozaguts thanks but same error :(
@bobbyadamski solution is still the only one that works for me.

**Comment by Marahin** [comment]
I have the exact same issue as @ThinkingAbout, however, I'm unable to force the dependencies and their versions lower.
