### ISSUE TITLE
fix: render function overloading

### ISSUE THREAD

**Issue by nestle49** [nuxt-community/composition-api#647]
**🐛 The bug**
render function works with 2 params h(type, data) or h(type, children), but doesn't work with 3 params: h('div', {}, children)

**🛠️ To reproduce**

1. use h() with 3 params
2. Children not render

**Comment by nestle49** [comment]
> This is likely an upstream issue with Vue itself. Would you investigate if so and raise an issue there?

It's work, if i import h() from Vue:

import Vue, { CreateElement, VNode } from 'vue';
h('div', { style: containerStyle }, columns)

but if i use h() from nuxt/composition-api, get this problem => I think the problem of nuxt/composition-api

Also, have the same bug
 https://github.com/nuxt-community/composition-api/issues/588
 
 Sorry for my English

**Comment by danielroe** [comment]
In that case, would you provide a reproduction, please? 🙏

**Comment by danielroe** [comment]
The latest version of nuxt/composition-api no longer includes `@vue/composition-api`. Would you check with the latest version to see if this is still an issue?

**Comment by nestle49** [comment]
> The latest version of nuxt/composition-api no longer includes `@vue/composition-api`. Would you check with the latest version to see if this is still an issue?
Yes, have problem with "@nuxtjs/composition-api": "^0.33.0"
