### ISSUE TITLE
help: useMeta is not working in SSG mode

### ISSUE THREAD

**Issue by iamandrewluca** [nuxt-community/composition-api#651]
**📚 What are you trying to do? Please describe.**

I'm having a website that is SSG rendered, and I have a page (`_slug.vue`) that uses `useMeta` inside `setup` and sets meta based on the slug, but it seems the final HTML does not contain that meta 🤔 

**🔍 What have you tried?**

I tried to create a empty Nuxt + Composition API project with this page. I removed title from `nuxt.config` to see if it works. After `npm run generate` the final `dist/index.html` is missing `<title>` tag at all

```ts
export default defineComponent({
  head: {},
  setup() {
    useMeta({ title: 'Hey!' })
  },
})
```

Manual adding to head inside setup will work

> Don't mind `vm.proxy` it's some internal Vue API
> `@nuxtjs/composition-api` uses their own internal `getCurrentInstance` that returns `proxy`, but exports the Vue `getCurrentInstance`

```ts
export default defineComponent({
  head: {},
  setup() {
    let vm = getCurrentInstance()
    vm.proxy.$options.head.title = 'Hey!'
  },
})
```

**ℹ️ Additional context**

```
node@16.15.1
npm@8.13.2
nuxt@2.15.8
vue@2.7.5
@nuxtjs/composition-api@0.33.0
```

ps: I moved back to Options API `head` for that page for now

**Comment by acibilous** [comment]
any updates?

**Comment by acibilous** [comment]
@iamandrewluca , make sure you are importing `defineComponent` from @nuxtjs/composition-api. It's not same in vue module))

**Comment by iamandrewluca** [comment]
@acibilous Thanks a lot! Didn't expect that 😀
