### ISSUE TITLE
fix: useAsync runing server and client at the same time

### ISSUE THREAD

**Issue by angularBBB** [nuxt-community/composition-api#652]
**🐛 The bug**
What isn't working? Describe what the bug is.

**🛠️ To reproduce**
<img width="540" alt="image" src="https://user-images.githubusercontent.com/26304597/178970127-45a7f79e-64f6-47b5-8ef9-48fd3b27cc37.png">

<img width="500" alt="image" src="https://user-images.githubusercontent.com/26304597/178970225-a33c8da7-e43b-40cd-ae76-ea0d92988d3e.png">

I use vue2.7 in setup  use "useAsync" it being executed in server and client  

**🌈 Expected behaviour**
useAsync only executed in server or client

**ℹ️ Additional context**
https://github.com/szptWangrs/nuxt-template.git

**Comment by danielroe** [comment]
`useAsync` is meant to return a value. If no value is returned it will run it again.

**Comment by aldarund** [comment]
@danielroe so useFetch cant be used to dispatch vuex calls, and useAsync cant be used to dispatch vuex calls ( as they store into state and not used directly retunred values usually). What left then?

**Comment by danielroe** [comment]
@aldarund You _can_ use it to do that: https://stackblitz.com/edit/github-s9qt7x?file=pages%2Findex.vue. But if you don't want it to be run more than once you will need to ensure a value - any value - is returned.

**Comment by aldarund** [comment]
@danielroe ye i though about it, not so clean solution but anyway. Btw if in your example return empty string instead of dict - it will break and will be called both client and server
