### ISSUE TITLE
help: useFetch works on client by default

### ISSUE THREAD

**Issue by nestle49** [nuxt-community/composition-api#657]
I migrate from fetch to useFetch of composition-api, have a problem:
useFetch works on client (from Nuxt docs, by default it's must be on server)

Fragment:
```
middleware: ['auth'],
async fetch(this: Page, context) {
            const { route, $pinia } = context;
            const globalStateStore = useGlobalStateStore($pinia);
            const appStore = useAppStore($pinia);

            if (!appStore.chainId) {
                globalStateStore.SET_PLATFORM({ platform: getPlatform(route.query) });

                await initializeApp(context);
            }
    }
```

And the same code with useFetch

```
export function usePage() {
    useFetch(async (ctx) => {
        const { $pinia, route } = ctx.$nuxt.context;
        const globalStateStore = useGlobalStateStore($pinia);
        const appStore = useAppStore($pinia);
        if (!appStore.chainId) {
            globalStateStore.SET_PLATFORM({ platform: getPlatform(route.query) });

            await initializeApp(ctx.$nuxt.context);
        }
    });

    return {};
}
```
Also I've tried set fetchOnServer false, but it don't work

```
<script lang="ts">
export default defineComponent({
    head: {},
    fetchOnServer: true
});
</script>
```

Can u help me, please? What's wrong?

**Comment by danielroe** [comment]
Would you provide a minimal reproduction? 🙏

**Comment by nestle49** [comment]
> Would you provide a minimal reproduction? 🙏

https://codesandbox.io/s/objective-surf-qd8p62?file=/pages/index.vue

1) Refresh index page, and get posts on server with fetch
2) Move on "Client" page, refresh page and useFetch from composition-api don't work, array of posts is empty

**Comment by danielroe** [comment]
Two things:

1. You will not be able to see the posts within your setup function as `async setup` is not supported in Vue 2.
2. You need to call useFetch on both sides. It won't repeat the fetch on client side, but it will fill out `posts.value` for you.
