### ISSUE TITLE
fix: When variable haves circular property, fails to deep copy in serverPrefetch.

### ISSUE THREAD

**Issue by kouwasi** [nuxt-community/composition-api#661]
**🐛 The bug**
When variable haves circular property, fails to deep copy in `serverPrefetch`.
Only in setup syntax sugar directive basically.

If return a circular variable intentionally, it may appear same issue.
Like this
```js
export default {
  setup() {
   // router haves circular property!
    const router = useRouter()
    const something = () => {
      router.push('/example')
    }

    return { router, something }
  }
}
```

I didn't test it yet, It's just my prediction.

**🛠️ To reproduce**
See my repository
https://github.com/kouwasi/nuxt-composition-circular-reproduce

**🌈 Expected behaviour**
Works correctly, even if variables have circular properties.

**ℹ️ Additional context**
Correctly filter variables in this section
https://github.com/nuxt-community/composition-api/blob/ae9307aec6b8f0b5c333f39238ea7339aa8fa411/src/runtime/composables/fetch.ts#L224-L235

Or do the deep copy with [fast-safe-stringify](https://github.com/davidmarkclements/fast-safe-stringify)

**Comment by danielroe** [comment]
The aim of `useFetch` is to match the Nuxt 2 `fetch` hook behaviour, and I don't believe circular variable references are supported there.

**Comment by kouwasi** [comment]
@danielroe 
Therefore, Can not use a circular variable in setup syntax sugar right?

**Comment by kouwasi** [comment]
I understood like the one above comment.
I gonna decided to use the defineComponent, 

Thanks for your reply.
