### ISSUE TITLE
Node engine

### ISSUE THREAD

**Issue by rchl** [nuxt-community/composition-api#662]
Was just wondering whether forcing latest minor/patch node version in:

https://github.com/nuxt-community/composition-api/blob/7c6bb1c061d75f3e3ea8d1a49d925f3f9f2114ff/package.json#L113

is a good idea in general.

If the older 14.* version has no obvious compatibility issues then limiting it to the latest seems unnecessary and problematic as it forces users of the package to use the latest node.

**Comment by danielroe** [comment]
You are right. This should be `>=14.13.0` for subpath import support.
