### ISSUE TITLE
 The requested module 'vue' does not provide an export named 'set'

### ISSUE THREAD

**Issue by Verdicts-ye** [nuxt-community/composition-api#666]
**🐛 The bug**
 The requested module 'vue' does not provide an export named 'set'

#  nuxt3  nuxt.config.ts
export default defineNuxtConfig({
  modules: [
    "@nuxtjs/composition-api",
    '@pinia/nuxt',
  ],
})

When module exists @nuxtjs/composition-api , this will cause problems

package.json

 "devDependencies": {
    "nuxt": "3.0.0-rc.6"
  },
  "dependencies": {
    "@nuxtjs/composition-api": "^0.33.1",
    "@pinia/nuxt": "^0.3.1",
    "axios": "^0.27.2",
    "element-plus": "^2.2.12",
    "jsonp": "^0.2.1",
    "pinia": "^2.0.17",
    "sass": "^1.54.2"
  }

**Comment by danielroe** [comment]
This module is only for Nuxt 2. You can safely remove it from your Nuxt 3 project.

**Comment by Verdicts-ye** [comment]
Thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Daniel ***@***.***&gt;; 
发送时间: 2022年8月4日(星期四) 下午2:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nuxt-community/composition-api]  The requested module &#39;vue&#39; does not provide an export named &#39;set&#39; (Issue #666)





 
Closed #666 as not planned.
 
&mdash;
