### ISSUE TITLE
help: compatibility @pinia/nux v0.2.1 with @nuxt/composition-api v0.33.1

### ISSUE THREAD

**Issue by nestle49** [nuxt-community/composition-api#667]
It's right that at the moment **@nuxt/composition-api** v**0.33.1** is incompatible with **@pinia/nuxt**": "^**0.2.1**"?

We use nuxt2 with "@pinia/nuxt": "^0.2.1" (last version of pinia compatible with nuxt2), next versions required **nuxt/bridge**

I get error:
`Cannot find module '@vue/composition-api'`
 
But if install and @vue/composition-api 
```
Could not resolve dependency:
npm ERR! peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.0
```

@danielroe can you suggest me please it's right or not and we can already use nuxt/bridge in production? Is it stable?

**Comment by danielroe** [comment]
It looks like you will need to use a lower level of `@nuxtjs/composition-api` as we now depend on Vue 2.7.

I would recommend you use `@nuxt/bridge`.
