### ISSUE TITLE
fix: ref, reactive, ... are not reexported from @nuxtjs/composition api

### ISSUE THREAD

**Issue by trinhngocdieu** [nuxt-community/composition-api#688]
**🐛 The bug**
Installing the `@nuxtjs/composition-api` to the codebase  that is currently using Nuxt 2, 
but can not use Composition-API (`ref`, `reactive`, ...), the error happened as following screenshot:

<img width="881" alt="Screen Shot 2022-09-05 at 16 17 35" src="https://user-images.githubusercontent.com/7900090/188398455-409cd79a-bb8a-4e08-a3c9-851b4b74b828.png">

**🌈 Expected behaviour**
Can use/import without error the `ref`, `reactive`, ... in the codebase.

**Comment by rchl** [comment]
You might have to update your dependencies with `npm upgrade` or `yarn upgrade`. Once you have the most recent version of Vue 2.7 and Nuxt then it should work. If not then feel free to provide a repo that reproduces.
