### ISSUE TITLE
fix: shallowSsrRef doesnt sync client and server in Nuxt

### ISSUE THREAD

**Issue by Mikephii** [nuxt-community/composition-api#711]
**🐛 The bug**

when creating a shallowSsrRef using the pattern described in docs, ref value is always reset to the intialiastion value provided to shallowSsrRef() on client. 

Server ref value will be returned by SSR and displayed on screen momentarily before client code runs and sets the shallowSsrRef to the initialisation value. Basically it doesnt work.

**🛠️ To reproduce**

1. create a shallowSsrRef intialise variable to shallowSsrRef({}, key)
2. populate variable in server side
3. ensure you are triggering ref update using trigger()
4. render variable to page 
5. load page and see serve value flashed before reset to client value

**🌈 Expected behaviour**
shallowSsrRef() should sync server and client just like ssrRef()

**ℹ️ Additional context**
Trying to use a shallow ref as i have a very large data object i am performing mutations on and stitching two sources of data together. deep reactive refs have an insertion time of 5ms (yuk) so doing about 50 mutations takes longer than a query. shallowRefs insert just as fast as normal objects but is unusuable for SSR becuase broken

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏
