### ISSUE TITLE
route.value: Cannot read properties of undefined (reading '_route') 

### ISSUE THREAD

**Issue by ThinkingAbout** [nuxt-community/composition-api#712]
**🐛 The bug**
Hi, the use of `route.value` now produces this error:

![Schermata 2022-10-12 alle 11 40 45](https://user-images.githubusercontent.com/682778/195310179-b070848e-fb71-4e96-9d2b-d959e36fbd16.png)

[Link stackblitz](https://stackblitz.com/edit/nuxt-starter-3qtx5w?file=pages%2Findex.vue)

Can someone please help?
Thanks,
Matteo

**Comment by rchl** [comment]
You need Vue 2.7.

Change your dependencies to:

```
    "@nuxtjs/composition-api": "^0.33.1",
    "core-js": "^3.29.1",
    "nuxt": "^2.16.3"
```

and run `npm upgrade` and it should work.
