### ISSUE TITLE
fix:  Error: Unknown file extension: [...]node_modules/pathe/dist/index.cjs 

### ISSUE THREAD

**Issue by ulfgebhardt** [nuxt-community/composition-api#735]
**🐛 The bug**
What isn't working? Describe what the bug is.

Using the version `0.33.x` of `@nuxtjs/composition-api` results in module resolution errors on our end.

![image](https://user-images.githubusercontent.com/1238238/210629962-cb26e276-8f16-4659-a6d3-90f78161b726.png)

This seems to be the case because of the usage of `pathe`.
The version `0.32.0` works as expected. `pathe` seems not to be present there.

**🛠️ To reproduce**

I cannot offer a repro, just have a link of a Open-Source Software where it works, and where it doesnt work

Not working: https://github.com/Ocelot-Social-Community/Ocelot-Social/pull/5843/commits/be41815b1abbaba403396ab1813e0c823fff6ec8
See Build Error on CI: https://github.com/Ocelot-Social-Community/Ocelot-Social/actions/runs/3838022136/jobs/6533996209

Working: https://github.com/Ocelot-Social-Community/Ocelot-Social/pull/5843/commits/3889204f871df97b307401032900db7940913038

I can offer to test things if that helps.

Node Version is `16.19` and `19.3` with the same behaviour.

**🌈 Expected behaviour**
What did you expect to happen? Is there a section in the docs about this?

I expected paradise on the latest version but found it a version earlier

**ℹ️ Additional context**

If this issue does not provide enough information due to the missing repro consider to just close it.

**Comment by Tirokk** [comment]
Thanks for caring and offer a solution @ulfgebhardt 👍🏼

**Comment by Tirokk** [comment]
Will be solved by #5843

**Comment by rchl** [comment]
Nuxt handles *.cjs files from version 2.16.0 so you might have to update your project to at least that version.

Otherwise you'd have to manually apply a fix similar to https://github.com/nuxt/nuxt/pull/10340 to make it work.
