### ISSUE TITLE
help: Cannot call useContext() inside watch() callback

### ISSUE THREAD

**Issue by tdoan2010** [nuxt-community/composition-api#736]
**📚 What are you trying to do? Please describe.**
I'm trying to do something when the `route.value.query` changes.

**🔍 What have you tried?**
My component looks like this:

```javascript
import { defineComponent, useContext, useRoute, watch } from '@nuxtjs/composition-api';

export default defineComponent({
  setup () {
    const route = useRoute();

    // Other code...

    watch(() => route.value.query, () => {
      const { $axios } = useContext();
    });

    // Other code...
  }
});
```

However, this gives me the error:

```
Error: This must be called within a setup function.
    at useContext (index.mjs?9a99:220:1)
    at eval (search.vue?9447:34:1)
    at invokeWithErrorHandling (vue.common.dev.js?4650:3634:1)
    at call (vue.common.dev.js?4650:3271:1)
    at watcher.run (vue.common.dev.js?4650:3375:1)
    at flushSchedulerQueue (vue.common.dev.js?4650:3140:1)
    at Array.eval (vue.common.dev.js?4650:3760:1)
    at flushCallbacks (vue.common.dev.js?4650:3682:1)
```

**ℹ️ Additional context**
I'm using [`@nuxtjs/composition-api`](https://composition-api.nuxtjs.org/) version 0.33.1 with Nuxt 2

**Comment by tdoan2010** [comment]
Is it the limitation of the `@nuxtjs/composition-api` package? Or of Vue?

It's quite cumbersome, when there are function calls inside the callback, and `$axios` must always be part of the function parameters.

**Comment by danielroe** [comment]
This is how the composition API generally works in Vue - you call the 'use*' functions up front and then use them in any non-synchronous callbacks or helper functions.
