### ISSUE TITLE
help: Failed to compile with 1 errors * @nuxtjs/composition-api in ./.nuxt/composition-api/meta.mjs

### ISSUE THREAD

**Issue by grosiak1204** [nuxt-community/composition-api#737]
**📚 What are you trying to do? Please describe.**
I wanted to install and test Pinia on my Nuxt 2 application.
Nuxt version 2.15.8, Nodejs version 14.21.1, Vue version 2.7.14.
I did the following:
Installed Pinia and Composition Api:
npm install pinia @pinia/nuxt@0.2.1 @nuxtjs/composition-api
then in nuxt.config.js file in buildModules I added:
 '@nuxtjs/composition-api/module',
 ['@pinia/nuxt', { disableVuex: false }]
Then when I run npm run dev, I get the following errror message:
Failed to compile with 1 errors 
* @nuxtjs/composition-api in ./.nuxt/composition-api/meta.mjs

**🔍 What have you tried?**
I have checked package.json
In dependencies everything is there:
"@nuxtjs/composition-api": "^0.33.1"
"@pinia/nuxt": "^0.2.1"
"pinia": "^2.0.28"

Checked .nuxt and node_modules files:
In .nuxt and node_modules/@nuxtjs composition-api is there

I tried again to install composition api with npm install --save @nuxtjs/composition-api, still the same error occurs when I run npm run dev

I have no other idea where the problem is.
Please help.
**ℹ️ Additional context**
Add any other context or information.

**Edit
in .nuxt/composition-api in meta.js and plugin.js I replaced '@nuxtjs/composition-api' with actual path '..../node_modules/@nuxtjs/composition-api/dist/runtime/index.js and after saving it works.
However, when I kill terminal and run npm run dev .nuxt is rewritten and '@nuxtjs/composition-api' comes back.
When I point a mouse on '@nuxtjs/composition-api' the path is like actual path, only there is no .js at the end.
It seems  '@nuxtjs/composition-api'  points to the wrong path.
How can I fix this?
I tried deleting .nuxt and running npm run dev again, but there is no change
I would be grateful for any help.

**Comment by grosiak1204** [comment]
I have manage to solve the problem. I had a full stop (period) in my app folder name. Previously it was working but Composition Api had problem with it. The moment I renamed my app file the problem was solved.

**Comment by rchl** [comment]
Not sure if this is a problem specific to this module but I'll assume that it's not important to look into it.
