### ISSUE TITLE
help: The setup binding property "$fetchState" is already declared.

### ISSUE THREAD

**Issue by amaury-tobias** [nuxt-community/composition-api#74]
**📚 What are you trying to do? Please describe.**
I using
```
const { $fetchState } = useFetch(async () => {
    articles.value = await app.$axios.$get('/articles')
 })
return { $fetchState }
```
and the console throw 
"ERROR  [Vue warn]: The setup binding property "$fetchState" is already declared."

**🔍 What have you tried?**
If I remove `$fetchState` from return the error don't appear but I can't use `$fetchState` on template

**ℹ️ Additional context**

**Comment by danielroe** [comment]
@amaury-tobias 

Yes, the `$tetchState` returned by `useFetch` is only for use in setup as there is already a `$fetchState` bound to the instance for use in the template.

When you say you can't use it in the template, what do you mean?

**Comment by amaury-tobias** [comment]
Yes i use Nuxt 2.12.2, in template like 
```
<p v-if="$fetchState.pending">Fetching posts...</p>
<p v-else-if="$fetchState.error">Error while fetching posts</p>
<p v-else> Loaded </p>
```
Now it's working, I think the browser cache caused it (I try to recreate the problem to report it, if appears).
So thank you for the information about $fetchState only can be used on the setup

**Comment by danielroe** [comment]
Great - glad things are working!
