### ISSUE TITLE
help: How to set 'noindex' for SEO for a specific component?

### ISSUE THREAD

**Issue by kentforth** [nuxt-community/composition-api#746]
How to set 'noindex' for SEO for a specific component on page?

**What a tried**
```export default defineComponent({
  name: 'Disclaimer',

  setup () {
    useMeta({
      title: '',
      hid: 'robots',
      name: 'robots',
      content: 'noindex'
    })
  },

  head: {}

})```

**Comment by rchl** [comment]
This is a question that is not specific to this module. Please read vue-meta documentation or at least https://nuxtjs.org/docs/components-glossary/head/
