### ISSUE TITLE
help: Computed property based on an object prop

### ISSUE THREAD

**Issue by rebinnaf** [nuxt-community/composition-api#750]
**📚 What are you trying to do? Please describe.**
I am not sure how to have an object prop without specific properties and then have a computed property based on it. I added a reproduction of my problem, I have a component that gets some data as prop and want to format it and then show it. But, although in the options api it is reactive, It is not reactive in composition api.

[Reproduction](https://codesandbox.io/p/sandbox/nostalgic-keldysh-k7onqm?file=%2Fpages%2Findex.vue&selection=%5B%7B%22endColumn%22%3A21%2C%22endLineNumber%22%3A16%2C%22startColumn%22%3A21%2C%22startLineNumber%22%3A16%7D%5D)

**🔍 What have you tried?**
If I define  `const field = ref({name:''}); ` it works but in my case I don't know what would be the response of the server

**ℹ️ Additional context**

**Comment by rchl** [comment]
I suppose this is a composition API question and not really specific to this module. You can probably do something like this in your component:

```ts
  setup(props) {
    const formattedName = computed(() => {
      if (props.field.name) {
        return `name:${props.field.name}`;
      }
    });
    return { formattedName };
  }
```
