### ISSUE TITLE
fix: Module should export a function: @nuxtjs/composition-api 

### ISSUE THREAD

**Issue by hakimov-dev** [nuxt-community/composition-api#759]
**🐛 The bug**
When i start my project i have problem

**🛠️ To reproduce**

1. I wrote `yarn dev`
2. 
![image](https://user-images.githubusercontent.com/83240328/235124036-770ab2ca-cb46-4678-b510-7b6f5e253ee0.png)

4. I See error

**🌈 Expected behaviour**
I expected run without bug

**Comment by hakimov-dev** [comment]
> 

![image](https://user-images.githubusercontent.com/83240328/235125996-6bd1440d-fa2b-4cb6-8514-520a4316f0f7.png)
I added it. But When i start my local server i see that bug.

**Comment by hakimov-dev** [comment]
Oh, I got it. Thanks u.

**Comment by danielroe** [comment]
You are very welcome.
