### ISSUE TITLE
help: i dont want any development at all on my phone

### ISSUE THREAD

**Issue by hoe1986** [nuxt-community/composition-api#90]
**📚 What are you trying to do? Please describe.**
A clear and concise description of your objective. Ex. I'm not sure how to [...].

**🔍 What have you tried?**
Have you looked through the docs? Tried different approaches? The more detail the better.

**ℹ️ Additional context**
Add any other context or information.

**Comment by danielroe** [comment]
@hoe1986 Looks like this issue might have been created in error. If not, please feel free to reply with more info and I'll reopen it.
