### ISSUE TITLE
feat: Why don't we have predefined verb for posting intermediate progress statement for xAPI statements?

### ISSUE THREAD

**Issue by apekshajha** [nuxt-community/composition-api#92]
**🆒 Your use case**
SumTotal is an LMS which has integrated with many content providers and import their content in our LMS. We are using xAPI to interact with the content providers to exchange details like start , completion and the score of the content. Our customers also want us to capture the
intermediate progress for content 
> Ex. When I do [...] I would expect to be able to do [...]

**🆕 The solution you'd like**
Have a standardized verb like 'Completed' to capture the intermediate progress percentage for content so that every provider do not define their own extension to capture the same

**🔍 Alternatives you've considered**
Have you considered any alternative solutions or features?
Extensions can be used to capture but it will only support just one provider. If it wont be standardized, it will be difficult to support multiple providers.

**ℹ️ Additional info**
Is there any other context you think would be helpful to know?

**Comment by danielroe** [comment]
@apekshajha Could you provide some more info on what you'd like from `nuxt-composition-api`? Are you talking about (for example) `useAsync`returning a status ref with the current status of the request (e.g. pending vs completed vs error)?

**Comment by apekshajha** [comment]
Thank you Daniel for instant reply. I think it should be posted https://github.com/adlnet/xAPI-Spec/issues/new
I will post the same there.

**Comment by danielroe** [comment]
@apekshajha Great - I'll close this issue but feel free to raise a new one if you experience any issues with `nuxt-composition-api` :slightly_smiling_face:
